#!/usr/bin/env python3
"""Вторая волна вопросов: теория + «что выведет» с понятными объяснениями."""
from __future__ import annotations


def q(topic, text, options, answer, explain, code=None):
    item = {
        "topic": topic,
        "q": text,
        "options": options,
        "answer": answer,
        "explain": explain,
    }
    if code:
        item["code"] = code
    return item


def build_junior() -> list[dict]:
    return [
        # ── строки / срезы ──
        q("строки", "Что выведет код?", ["'PyThOn'", "'PYTHON'", "'python'", "ошибка"], 0,
          "swapcase меняет регистр каждого символа на противоположный.",
          code="print('pYtHoN'.swapcase())"),
        q("строки", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "isdigit() True только если все символы — цифры. '½' и буквы — нет.",
          code="print('42'.isdigit())"),
        q("строки", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
          "'42a' содержит букву → isdigit() False.",
          code="print('42a'.isdigit())"),
        q("строки", "Что выведет код?", ["'a-b-c'", "'abc'", "['a','b','c']", "ошибка"], 0,
          "join склеивает элементы через разделитель слева.",
          code="print('-'.join(['a', 'b', 'c']))"),
        q("строки", "Что выведет код?", ["['a', 'b', 'c']", "['a b c']", "'a b c'", "ошибка"], 0,
          "split() без аргументов режет по пробелам.",
          code="print('a b c'.split())"),
        q("строки", "Что выведет код?", ["2", "3", "1", "0"], 0,
          "count считает непересекающиеся вхождения подстроки.",
          code="print('banana'.count('an'))"),
        q("строки", "Что выведет код?", ["'***hi'", "'hi***'", "'*hi*'", "ошибка"], 0,
          "rjust(5, '*') дополняет слева до ширины 5.",
          code="print('hi'.rjust(5, '*'))"),
        q("строки", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "endswith проверяет суффикс.",
          code="print('report.pdf'.endswith('.pdf'))"),
        q("строки", "f-string: что выведет?", ["'003'", "'3'", "'  3'", "ошибка"], 0,
          "{n:03d} — ширина 3, ведущие нули.",
          code="n = 3\nprint(f'{n:03d}')"),
        q("строки", "Что выведет код?", ["'HELLO'", "'Hello'", "'hello'", "ошибка"], 0,
          "upper() возвращает новую строку в верхнем регистре.",
          code="print('Hello'.upper())"),

        # ── списки ──
        q("списки", "Что выведет код?", ["[1, 2, 4, 3]", "[1, 2, 3, 4]", "[4]", "None"], 0,
          "insert(2, 4) вставляет 4 на индекс 2: было [1,2,3] → [1,2,4,3].",
          code="a = [1, 2, 3]\na.insert(2, 4)\nprint(a)"),
        q("списки", "Что выведет код?", ["3", "2", "[1, 2]", "ошибка"], 0,
          "pop() без аргумента снимает и возвращает последний элемент.",
          code="a = [1, 2, 3]\nprint(a.pop())"),
        q("списки", "Что выведет код?", ["[1, 3]", "[1, 2]", "[2, 3]", "ошибка"], 0,
          "remove удаляет первое вхождение значения 2.",
          code="a = [1, 2, 3]\na.remove(2)\nprint(a)"),
        q("списки", "Что выведет код?", ["[3, 2, 1]", "[1, 2, 3]", "None", "ошибка"], 0,
          "reverse() мутирует список на месте и возвращает None; print(a) показывает уже развёрнутый.",
          code="a = [1, 2, 3]\na.reverse()\nprint(a)"),
        q("списки", "Что вернёт list.reverse()?", ["None", "развёрнутый список", "True", "ошибка"], 0,
          "Как и sort(), reverse() возвращает None."),
        q("списки", "Что выведет код?", ["[1, 2, 3, 1, 2, 3]", "[1, 2, 3]", "ошибка", "[[1,2,3],[1,2,3]]"], 0,
          "Умножение списка на int повторяет ссылки на элементы.",
          code="print([1, 2, 3] * 2)"),
        q("списки", "Что выведет код?", ["[0, 0, 0]", "[0]", "ошибка", "None"], 0,
          "[0] * 3 создаёт список из трёх нулей.",
          code="print([0] * 3)"),
        q("списки", "Ловушка: что будет с b?", ["[[1], [1], [1]]", "[[1], [], []]", "ошибка", "[[], [], []]"], 0,
          "a = [[]] * 3 — три ссылки на ОДИН внутренний список. a[0].append(1) меняет все.",
          code="a = [[]] * 3\na[0].append(1)\nprint(a)"),
        q("списки", "Как правильно сделать 3 независимых списка?",
          ["[[] for _ in range(3)]", "[[]] * 3", "list(3 * [])", "[None] * 3"], 0,
          "List comprehension создаёт новый [] на каждой итерации."),
        q("списки", "Что выведет код?", ["2", "1", "0", "ошибка"], 0,
          "index возвращает индекс первого вхождения.",
          code="print([10, 20, 30, 20].index(30))"),

        # ── словари / множества ──
        q("словари", "Что выведет код?", ["1", "0", "KeyError", "None"], 0,
          "setdefault ставит значение только если ключа ещё нет; здесь 'a' уже есть → 1.",
          code="d = {'a': 1}\nprint(d.setdefault('a', 99))"),
        q("словари", "Что выведет код?", ["99", "None", "KeyError", "0"], 0,
          "Ключа 'b' не было — setdefault добавит 99 и вернёт его.",
          code="d = {'a': 1}\nprint(d.setdefault('b', 99))"),
        q("словари", "Что выведет код?", ["['a', 'b']", "[1, 2]", "dict_keys(['a','b']) как list", "ошибка"], 0,
          "list(dict) / list(keys()) — список ключей.",
          code="print(list({'a': 1, 'b': 2}.keys()))"),
        q("словари", "Что выведет код?", ["2", "1", "KeyError", "None"], 0,
          "pop удаляет ключ и возвращает значение.",
          code="d = {'a': 1, 'b': 2}\nprint(d.pop('b'))"),
        q("словари", "Что выведет код?", ["{'a': 1, 'b': 2, 'c': 3}", "{'c': 3}", "ошибка", "{'a':1}"], 0,
          "update добавляет/перезаписывает пары из другого dict.",
          code="d = {'a': 1, 'b': 2}\nd.update({'c': 3})\nprint(d)"),
        q("словари", "Можно ли ключом dict сделать список?",
          ["нет, TypeError", "да", "да, если пустой", "только в 3.12+"], 0,
          "Ключ должен быть hashable. list — нет."),
        q("множества", "Что выведет код?", ["{1, 2, 3}", "{1, 2}", "{3}", "ошибка"], 0,
          "| — объединение множеств.",
          code="print({1, 2} | {2, 3})"),
        q("множества", "Что выведет код?", ["{2}", "{1, 2, 3}", "set()", "ошибка"], 0,
          "& — пересечение.",
          code="print({1, 2} & {2, 3})"),
        q("множества", "Что выведет код?", ["{1}", "{1, 2, 3}", "{3}", "ошибка"], 0,
          "- — разность: элементы левого, которых нет в правом.",
          code="print({1, 2} - {2, 3})"),
        q("множества", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "issubset: {1,2} ⊆ {1,2,3}.",
          code="print({1, 2}.issubset({1, 2, 3}))"),

        # ── операторы / bool ──
        q("операторы", "Что выведет код?", ["'b'", "'a'", "True", "ошибка"], 0,
          "or возвращает первый истинный операнд (не обязательно bool).",
          code="print('' or 'b')"),
        q("операторы", "Что выведет код?", ["''", "'b'", "False", "ошибка"], 0,
          "and возвращает первый ложный; '' ложен.",
          code="print('' and 'b')"),
        q("операторы", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
          "is сравнивает идентичность объектов, == — равенство значений. Два разных списка.",
          code="print([1] is [1])"),
        q("операторы", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "Значения равны.",
          code="print([1] == [1])"),
        q("операторы", "Что выведет код?", ["5", "4", "3", "ошибка"], 0,
          "Сначала ** (2**2=4), потом +: 1+4=5.",
          code="print(1 + 2 ** 2)"),
        q("операторы", "Что выведет код?", ["-4", "-3", "3", "ошибка"], 0,
          "// округляет вниз (к −∞): -7/2 = -3.5 → -4.",
          code="print(-7 // 2)"),
        q("сравнения", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "Цепочка сравнений: 1 < 2 и 2 < 3.",
          code="print(1 < 2 < 3)"),
        q("сравнения", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
          "1 < 2 истинно, но 2 > 3 ложно → вся цепочка False.",
          code="print(1 < 2 > 3)"),

        # ── циклы / range / enumerate ──
        q("циклы", "Что выведет код?", ["0\n1\n2", "1\n2\n3", "0\n1\n2\n3", "ошибка"], 0,
          "range(3) → 0,1,2.",
          code="for i in range(3):\n    print(i)"),
        q("циклы", "Что выведет код?", ["1", "0", "2", "ничего"], 0,
          "break выходит сразу; else у for выполняется только без break — здесь не сработает. Печатается 1.",
          code="for i in range(3):\n    if i == 1:\n        print(i)\n        break\nelse:\n    print('done')"),
        q("циклы", "Что выведет код?", ["done", "2", "0", "ошибка"], 0,
          "Цикл завершился без break → сработал else.",
          code="for i in range(3):\n    pass\nelse:\n    print('done')"),
        q("встроенные", "Что выведет код?", ["[(1, 'a'), (2, 'b')]", "[(0, 'a'), (1, 'b')]", "ошибка", "['a','b']"], 0,
          "enumerate(..., start=1) начинает счёт с 1.",
          code="print(list(enumerate('ab', start=1)))"),
        q("zip", "Что выведет код?", ["[(1, 'a')]", "[(1,'a'),(2,'b')]", "ошибка", "[]"], 0,
          "zip обрезает по самому короткому итерируемому.",
          code="print(list(zip([1, 2], ['a'])))"),

        # ── comprehensions / функции ──
        q("listcomp", "Что выведет код?", ["[1, 4, 9]", "[1, 2, 3]", "[0, 1, 4]", "ошибка"], 0,
          "Квадраты 1,2,3.",
          code="print([x * x for x in range(1, 4)])"),
        q("listcomp", "Что выведет код?", ["[2, 4]", "[1, 2, 3, 4]", "[1, 3]", "ошибка"], 0,
          "Фильтр чётных.",
          code="print([x for x in range(1, 5) if x % 2 == 0])"),
        q("dict", "Что выведет код?", ["{0: 0, 1: 1, 2: 4}", "{0, 1, 4}", "ошибка", "[0,1,4]"], 0,
          "Dict comprehension: ключ i, значение i*i.",
          code="print({i: i * i for i in range(3)})"),
        q("функции", "Что выведет код?", ["1 2 3", "6", "(1, 2, 3)", "ошибка"], 0,
          "*args собирает позиционные в кортеж; print разворачивает.",
          code="def f(*args):\n    print(*args)\nf(1, 2, 3)"),
        q("функции", "Что выведет код?", ["{'a': 1}", "a=1", "1", "ошибка"], 0,
          "**kwargs — словарь именованных аргументов; print печатает {'a': 1}.",
          code="def f(**kw):\n    print(kw)\nf(a=1)"),
        q("функции", "Что выведет код?", ["[1, 1]", "[1]", "[]", "ошибка"], 0,
          "Mutable default один на все вызовы: после первого f() список уже [1], второй append → [1, 1].",
          code="def f(x=[]):\n    x.append(1)\n    return x\nf()\nprint(f())"),
        q("функции", "Безопасный default для списка?",
          ["def f(x=None):\\n    if x is None: x = []", "def f(x=[]):", "def f(x=list):", "нельзя"], 0,
          "Создавай новый список внутри, если аргумент не передан."),
        q("lambda", "Что выведет код?", ["9", "6", "ошибка", "None"], 0,
          "lambda x: x*x вызывается с 3.",
          code="print((lambda x: x * x)(3))"),

        # ── исключения / файлы / прочее ──
        q("ошибки", "Что выведет код?", ["ok", "ZeroDivisionError", "ничего", "ошибка синтаксиса"], 0,
          "except перехватывает ZeroDivisionError, печатает ok.",
          code="try:\n    1 / 0\nexcept ZeroDivisionError:\n    print('ok')"),
        q("ошибки", "Что выведет код?", ["1", "2", "ошибка", "None"], 0,
          "finally с pass не меняет return из try → функция возвращает 1.",
          code="def f():\n    try:\n        return 1\n    finally:\n        pass\nprint(f())"),
        q("ошибки", "Если и в try, и в finally есть return — что вернётся?",
          ["значение из finally", "значение из try", "None", "ошибка"], 0,
          "return в finally перекрывает return из try/except."),
        q("ошибки", "Что выведет код?", ["from finally", "from try", "ошибка", "None"], 0,
          "return в finally побеждает — наружу уйдёт 'from finally'.",
          code="def f():\n    try:\n        return 'from try'\n    finally:\n        return 'from finally'\nprint(f())"),
        q("типы", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "isinstance учитывает наследование; bool ⊂ int.",
          code="print(isinstance(True, int))"),
        q("типы", "Что выведет код?", ["int", "float", "str", "ошибка"], 0,
          "int('42') парсит строку в целое.",
          code="print(type(int('42')).__name__)"),
        q("кортежи", "Что выведет код?", ["(1, 2, 3, 4)", "(1, 2, [3, 4])", "ошибка", "[1,2,3,4]"], 0,
          "Конкатенация кортежей создаёт новый кортеж.",
          code="print((1, 2) + (3, 4))"),
        q("кортежи", "t = (1); type(t)?", ["int", "tuple", "list", "ошибка"], 0,
          "Без запятой (1) — просто int в скобках. Кортеж: (1,)."),
        q("кортежи", "Что выведет код?", ["tuple", "int", "list", "ошибка"], 0,
          "Запятая делает кортеж.",
          code="print(type((1,)).__name__)"),
        q("встроенные", "Что выведет код?", ["[3, 2, 1]", "[1, 2, 3]", "None", "ошибка"], 0,
          "sorted(..., reverse=True) — новый список по убыванию.",
          code="print(sorted([1, 3, 2], reverse=True))"),
        q("встроенные", "Что выведет код?", ["'ccc'", "'aa'", "'b'", "ошибка"], 0,
          "max с key=len выбирает самую длинную строку — 'ccc'.",
          code="print(max(['aa', 'b', 'ccc'], key=len))"),
        q("встроенные", "any([0, 0, 5])?", ["True", "False", "5", "ошибка"], 0,
          "any истинен, если хотя бы один элемент truthy."),
        q("встроенные", "all([1, 2, 0])?", ["False", "True", "0", "ошибка"], 0,
          "all ложен, если есть falsy (0)."),
        q("модули", "Как импортировать только sqrt из math?",
          ["from math import sqrt", "import math.sqrt", "include math.sqrt", "using math.sqrt"], 0,
          "from module import name."),
        q("файлы", "Режим 'a' у open — это…",
          ["дозапись в конец / создание", "только чтение", "перезапись с нуля", "бинарный"], 0,
          "append: пишет в конец файла."),
        q("файлы", "with open(...) as f: зачем?",
          ["гарантирует закрытие файла", "быстрее читает", "блокирует GC", "нужен только для бинарных"], 0,
          "Контекстный менеджер вызывает f.close() даже при ошибке."),
    ]


def build_middle() -> list[dict]:
    return [
        # ── OOP ──
        q("ООП", "Что выведет код?", ["B", "A", "ошибка", "None"], 0,
          "Метод ищется в классе экземпляра: B.hello перекрывает A.hello.",
          code="class A:\n    def hello(self):\n        return 'A'\nclass B(A):\n    def hello(self):\n        return 'B'\nprint(B().hello())"),
        q("ООП", "Что выведет код?", ["A.x", "B.x", "ошибка", "None"], 0,
          "super().hello() вызывает реализацию родителя.",
          code="class A:\n    def hello(self):\n        return 'A.x'\nclass B(A):\n    def hello(self):\n        return super().hello()\nprint(B().hello())"),
        q("ООП", "@property обычно…",
          ["даёт доступ как к атрибуту, считая через метод", "делает метод статическим", "удаляет атрибут", "только для private"], 0,
          "obj.x вызывает getter без скобок."),
        q("ООП", "Что выведет код?", ["3", "ошибка", "None", "0"], 0,
          "property x читает _x.",
          code="class C:\n    def __init__(self):\n        self._x = 3\n    @property\n    def x(self):\n        return self._x\nprint(C().x)"),
        q("ООП", "__init__ vs __new__?",
          ["__new__ создаёт объект, __init__ инициализирует", "синонимы", "__init__ создаёт, __new__ нет", "только __init__ существует"], 0,
          "__new__ — конструктор (редко нужен), __init__ — инициализатор."),
        q("ООП", "MRO при diamond: C(A,B) порядок?",
          ["C → A → B → object (примерно, C3)", "C → B → A всегда", "случайный", "ошибка всегда"], 0,
          "C3 linearization; смотри Class.__mro__."),
        q("ООП", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "issubclass(bool, int) — True.",
          code="print(issubclass(bool, int))"),
        q("ООП", "__slots__ зачем?",
          ["фиксирует атрибуты, экономит память (нет __dict__)", "ускоряет import", "включает GIL", "нужен для async"], 0,
          "Экземпляры без произвольных атрибутов."),
        q("ООП", "classmethod получает…",
          ["класс (cls), не экземпляр", "только self", "модуль", "метакласс всегда"], 0,
          "Удобно для альтернативных конструкторов."),
        q("ООП", "staticmethod — это…",
          ["функция в классе без self/cls", "то же что classmethod", "абстрактный метод", "property"], 0,
          "Не получает ни экземпляр, ни класс автоматически."),

        # ── декораторы / замыкания ──
        q("декораторы", "Что выведет код?", ["wrap", "f", "ошибка", "None"], 0,
          "Без functools.wraps у обёртки остаётся имя wrap, не f.",
          code="def deco(fn):\n    def wrap():\n        return fn()\n    return wrap\n@deco\ndef f():\n    pass\nprint(f.__name__)"),
        q("декораторы", "functools.wraps помогает…",
          ["сохранить __name__/__doc__ исходной функции", "ускорить вызов", "убрать GIL", "сделать async"], 0,
          "Копирует метаданные на обёртку."),
        q("замыкания", "Что выведет код?", ["[2, 2, 2]", "[0, 1, 2]", "[1, 1, 1]", "ошибка"], 0,
          "Все lambda закрывают одну переменную i; после цикла i==2.",
          code="fs = [lambda: i for i in range(3)]\nprint([f() for f in fs])"),
        q("замыкания", "Как починить late binding в цикле?",
          ["lambda i=i: i  (default аргумент)", "только global", "нельзя", "использовать list обязательно"], 0,
          "Default фиксирует значение на каждой итерации."),
        q("замыкания", "Что выведет код?", ["[0, 1, 2]", "[2, 2, 2]", "ошибка", "[1, 2, 3]"], 0,
          "i=i в default сохраняет текущее i.",
          code="fs = [lambda i=i: i for i in range(3)]\nprint([f() for f in fs])"),

        # ── генераторы / итераторы ──
        q("генераторы", "Что выведет код?", ["0\n1\n2", "3", "[0,1,2]", "ошибка"], 0,
          "yield отдаёт значения по одному.",
          code="def g():\n    yield 0\n    yield 1\n    yield 2\nfor x in g():\n    print(x)"),
        q("генераторы", "Что делает next(gen) на исчерпанном генераторе?",
          ["StopIteration", "None", "False", "перезапуск"], 0,
          "Итератор закончился."),
        q("генераторы", "gen = (x for x in range(3)); list(gen); list(gen) второй раз?",
          ["[]", "[0,1,2]", "ошибка", "[0,1,2] снова"], 0,
          "Генератор одноразовый — после exhaust пусто."),
        q("генераторы", "Что выведет код?", ["1", "0", "None", "ошибка"], 0,
          "Первый next() доходит до первого yield и отдаёт 1.",
          code="def g():\n    x = yield 1\n    yield x\ngen = g()\nprint(next(gen))"),
        q("итераторы", "iter(obj) ожидает…",
          ["__iter__ или __getitem__", "только len", "только __next__", "pickle"], 0,
          "Протокол итерации."),
        q("итераторы", "Что выведет код?", ["1", "StopIteration сразу", "None", "[1,2]"], 0,
          "iter по списку; next берёт первый элемент.",
          code="print(next(iter([1, 2])))"),

        # ── itertools / collections ──
        q("itertools", "Что выведет list(itertools.chain([1], [2, 3]))?",
          ["[1, 2, 3]", "[[1],[2,3]]", "ошибка", "[1]"], 0,
          "chain склеивает итерируемые подряд."),
        q("itertools", "Что выведет код?", ["[(1, 2), (3, 4)]", "[1,2,3,4]", "ошибка", "[(1,2,3,4)]"], 0,
          "batched(n) группирует по n (3.12+). Если нет — skip? Better use classic:",
          code="from itertools import islice\nit = iter([1, 2, 3, 4])\nprint([tuple(islice(it, 2)), tuple(islice(it, 2))])"),
        q("itertools", "product('ab', repeat=2) даёт…",
          ["aa ab ba bb (как кортежи)", "только ab", "перестановки без повторов", "ошибка"], 0,
          "Декартово произведение."),
        q("collections", "Counter('aab')['a']?", ["2", "1", "3", "ошибка"], 0,
          "Счётчик частоты."),
        q("collections", "defaultdict(list): d['x'].append(1) — что с d['x']?",
          ["[1], ключ создался сам", "KeyError", "None", "ошибка типа"], 0,
          "Фабрика list() вызывается для отсутствующего ключа."),
        q("collections", "namedtuple удобен тем, что…",
          ["immutable + доступ по имени поля", "мутабельный dict", "замена list", "async queue"], 0,
          "Лёгкие записи без класса вручную."),
        q("collections", "deque.popleft() сложность?",
          ["O(1)", "O(n) как list.pop(0)", "O(log n)", "O(n²)"], 0,
          "Для очередей deque лучше list."),

        # ── typing / dataclass / context ──
        q("typing", "list[int] в аннотации (3.9+) значит…",
          ["подсказка типов, на runtime не проверяет сама", "runtime проверка всегда", "создаёт typed list", "запрещает append str"], 0,
          "Проверяют mypy/pyright, не CPython по умолчанию."),
        q("typing", "Optional[str] эквивалент…",
          ["str | None", "str | int", "Union[str, int]", "Any"], 0,
          "Значение str либо None."),
        q("dataclass", "@dataclass генерирует…",
          ["__init__/__repr__/__eq__ и др. по полям", "только __slots__", "async методы", "SQL схему"], 0,
          "Меньше бойлерплейта для data-классов."),
        q("dataclass", "field(default_factory=list) зачем?",
          ["свой список на каждый экземпляр", "общий список на класс", "быстрее int", "для slots only"], 0,
          "Как безопасный mutable default."),
        q("context", "Что выведет код?", ["enter\nexit", "enter", "exit", "ошибка"], 0,
          "__enter__ затем тело, затем __exit__.",
          code="class CM:\n    def __enter__(self):\n        print('enter')\n        return self\n    def __exit__(self, *a):\n        print('exit')\nwith CM():\n    pass"),
        q("context", "contextlib.contextmanager превращает…",
          ["генератор с одним yield в context manager", "async в sync", "класс в функцию", "list в set"], 0,
          "Код до yield — enter, после — exit."),
        q("исключения", "raise X from Y связывает…",
          ["__cause__ для цепочки исключений", "только traceback hide", "logging level", "warning"], 0,
          "Явная причинная связь."),
        q("исключения", "except Exception не ловит…",
          ["BaseException вроде KeyboardInterrupt/SystemExit", "ValueError", "TypeError", "RuntimeError"], 0,
          "Exception ⊂ BaseException; Ctrl+C не глотай без нужды."),

        # ── asyncio / concurrency mid ──
        q("asyncio", "await можно внутри…",
          ["async def", "обычного def", "класса без async", "import"], 0,
          "Иначе SyntaxError."),
        q("asyncio", "asyncio.gather(*tasks) …",
          ["запускает конкурентно и ждёт все", "строго последовательно", "только первый", "убивает loop"], 0,
          "Параллельные awaitables."),
        q("asyncio", "create_task vs await coro сразу?",
          ["create_task планирует в фоне event loop", "синонимы", "create_task блокирует поток", "запрещено"], 0,
          "Task начинает выполняться, пока ты делаешь другое."),
        q("concurrency", "GIL мешает…",
          ["параллельному CPU-коду в потоках CPython", "любому I/O", "multiprocessing", "asyncio I/O"], 0,
          "I/O и multiprocessing — обходы."),
        q("concurrency", "Когда threading уместен?",
          ["много I/O ожидания", "чистый CPU без release GIL", "вместо процессов всегда", "только Windows"], 0,
          "Пока ждёшь сеть/диск, другой поток может работать."),

        # ── stdlib mid code ──
        q("json", "json.loads('[1, 2]') вернёт…", ["[1, 2]", "'[1, 2]'", "tuple", "ошибка"], 0,
          "loads парсит JSON-строку в Python-объект."),
        q("json", "json.dumps({1: 'a'}) ключ станет…",
          ["строкой '1'", "int 1 в JSON", "байтами", "ошибка всегда"], 0,
          "JSON keys — строки."),
        q("pathlib", "Path('a') / 'b' даёт…",
          ["Path('a/b') (или с \\ на Windows)", "строку 'a/b' всегда", "ошибка", "list"], 0,
          "Оператор / у Path."),
        q("регулярки", "re.findall(r'\\d+', 'a12b3')?",
          ["['12', '3']", "['1','2','3']", "['a12b3']", "[]"], 0,
          "Все группы цифр подряд."),
        q("copy", "copy.copy vs deepcopy?",
          ["shallow копирует верх, nested — ссылки; deep — рекурсивно", "синонимы", "copy всегда deep", "deepcopy только list"], 0,
          "Для вложенных мутабельных нужен deepcopy."),
        q("copy", "Что выведет код?", ["[1]", "[]", "ошибка", "[0]"], 0,
          "shallow: внутренний list общий.",
          code="import copy\na = [[]]\nb = copy.copy(a)\na[0].append(1)\nprint(b[0])"),
        q("args", "def f(a, /, b, *, c): — как вызвать верно?",
          ["f(1, 2, c=3) или f(1, b=2, c=3)", "f(a=1, b=2, c=3)", "f(1, 2, 3)", "f(c=3, 1, 2)"], 0,
          "a только позиционно; c только по имени; b — оба способа."),
        q("функции", "Что выведет код?", ["(1, 2)", "1", "ошибка", "[1,2]"], 0,
          "Функция возвращает кортеж.",
          code="def f():\n    return 1, 2\nprint(f())"),
        q("comprehensions", "[(x, y) for x in range(2) for y in range(2)] длина?",
          ["4", "2", "3", "ошибка"], 0,
          "Декартово 2×2."),
        q("walrus", "Что выведет код?", ["5", "True", "ошибка", "None"], 0,
          ":= присваивает n и использует в выражении.",
          code="if (n := len('hello')) > 3:\n    print(n)"),
        q("f-string", "Что выведет код?", ["'x=10'", "'10'", "'x={x}'", "ошибка"], 0,
          "Отладочный = в f-string (3.8+).",
          code="x = 10\nprint(f'{x=}')"),
        q("bytes", "b'hi'.decode() по умолчанию…",
          ["utf-8 → 'hi'", "ascii only fail", "latin-1 always error", "возвращает bytes"], 0,
          "decode() без encoding → utf-8."),
        q("строки", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "casefold сильнее lower для регистронезависимого сравнения (напр. немецкое ß).",
          code="print('X'.casefold() == 'x')"),
    ]


def build_senior() -> list[dict]:
    return [
        q("GIL", "GIL в CPython — это…",
          ["mutex на выполнение байткода в одном процессе", "запрет потоков ОС", "замена multiprocessing", "только в PyPy"], 0,
          "Один поток выполняет Python-байткод; I/O и C-ext могут отпускать GIL."),
        q("GIL", "free-threading (PEP 703) цель…",
          ["опционально убрать GIL, дать истинный параллелизм потоков", "удалить asyncio", "запретить C-API", "ускорить только import"], 0,
          "Большой сдвиг runtime в 3.13+ experimental."),
        q("CPython", "Что хранит PyObject заголовок примерно?",
          ["refcount + указатель на тип", "только значение", "только GC next", "имя переменной"], 0,
          "База любого managed-объекта."),
        q("CPython", "interning маленьких int…",
          ["кэш часто используемых int (детали зависят от версии/build)", "все int всегда unique", "только float", "только str ascii"], 0,
          "Поэтому is у маленьких int может быть True «случайно» — для идентичности не опирайся."),
        q("CPython", "dis.dis(f) показывает…",
          ["байткод функции", "AST", "машинный код CPU", "GIL state"], 0,
          "Дизассемблер байткода."),
        q("память", "цикл ссылок a.x=b; b.x=a собирает…",
          ["generational GC (цикл), не только refcount", "только refcount сразу", "никогда", "только weakref"], 0,
          "refcount не рвёт циклы сам — нужен cyclic GC."),
        q("память", "weakref.ref(obj) нужен чтобы…",
          ["ссылаться без удержания объекта от GC", "ускорить dict", "заменить deepcopy", "отключить GIL"], 0,
          "Кэши, наблюдатели, canonical maps."),
        q("asyncio", "что такое backpressure?",
          ["торможение производителя, когда потребитель не успевает", "увеличение concurrency always", "GIL pause", "DNS cache"], 0,
          "Очереди с maxsize, потоки с паузами."),
        q("asyncio", "shield(awaitable) …",
          ["защищает от отмены снаружи", "ускоряет", "делает multithread", "игнорирует exceptions"], 0,
          "Отмена task снаружи не пробрасывается внутрь shield (с нюансами)."),
        q("asyncio", "TaskGroup (3.11+) даёт…",
          ["structured concurrency: ошибки/отмена детей согласованы", "только gather без ошибок", "thread pool", "GIL off"], 0,
          "Предпочтительнее «голого» gather в новом коде."),
        q("concurrency", "multiprocessing почему обходит GIL?",
          ["отдельные процессы → свой интерпретатор/память", "отключает GIL в родителе", "использует greenlet", "только Windows fibers"], 0,
          "Цена: pickle/IPC и память."),
        q("concurrency", "concurrent.futures.ProcessPoolExecutor хорош для…",
          ["CPU-bound кусков", "крошечных print", "замены asyncio всегда", "GUI main thread"], 0,
          "Пул процессов с future API."),
        q("concurrency", "False sharing — это…",
          ["ядра бьются за одну cache line разных переменных", "ошибка GIL", "asyncio bug", "pickle fail"], 0,
          "Низкоуровневый perf в native/parallel коде."),
        q("дескрипторы", "__get__/__set__/__delete__ — протокол…",
          ["дескрипторов (property — частный случай)", "только metaclasses", "async context", "import hooks"], 0,
          "Управляют доступом к атрибутам."),
        q("дескрипторы", "data vs non-data descriptor?",
          ["наличие __set__/__delete__ меняет приоритет в lookup", "нет разницы", "только slots", "только slots + GC"], 0,
          "Data descriptor побеждает instance __dict__."),
        q("метаклассы", "type(name, bases, ns) создаёт…",
          ["новый класс", "экземпляр object", "модуль", "coroutine"], 0,
          "Классы — объекты type."),
        q("метаклассы", "class A(metaclass=M) вызывает…",
          ["M(...) при создании класса", "M при каждом инстансе only", "только importlib", "GC"], 0,
          "Метакласс контролирует создание класса."),
        q("typing", "Protocol (PEP 544) — это…",
          ["структурная типизация (duck typing для чекеров)", "runtime ABC обязательно", "замена ABC всегда", "GIL type"], 0,
          "Если есть нужные методы — подходит тип."),
        q("typing", "TypeVar bound=... ограничивает…",
          ["верхнюю границу допустимых типов", "только runtime cast", "скорость", "GIL"], 0,
          "Дженерики с ограничением."),
        q("typing", "@overload зачем?",
          ["описать разные сигнатуры для чекера", "ускорить вызовы", "создать runtime branches auto", "убрать kwargs"], 0,
          "Реализация одна — stubs/overloads для типов."),
        q("packaging", "pyproject.toml [project] — стандарт…",
          ["метаданных/сборки (PEP 621 и др.)", "только poetry proprietary", "замена requirements forever without lock", "CPython ini"], 0,
          "Единая точка конфигурации пакета."),
        q("packaging", "wheel vs sdist?",
          ["wheel — собранный дистрибутив; sdist — исходники для сборки", "синонимы", "wheel только win", "sdist быстрее install always"], 0,
          "Предпочитай wheels в проде для скорости/репродьюса."),
        q("security", "pickle.load из сети — риск?",
          ["RCE через произвольные объекты", "только DoS CPU", "безопасен всегда", "только XSS"], 0,
          "Никогда не unpickle недоверенное."),
        q("security", "secrets модуль лучше random для…",
          ["токенов/криптостойкой случайности", "shuffle списков UI", "range seed tests", "math.sin"], 0,
          "OS CSPRNG."),
        q("db", "N+1 проблема — это…",
          ["1 запрос + N запросов на связанные сущности", "N индексов", "N реплик", "1 транзакция"], 0,
          "Лечится join/prefetch/dataloader."),
        q("db", "READ COMMITTED не защищает от…",
          ["части anomalies (зависит от СУБД; phantom и т.д.)", "всего всегда", "только DDL", "только disk full"], 0,
          "Знай модель изоляции своей БД."),
        q("cache", "cache stampede / thundering herd…",
          ["толпа одновременных пересчётов одного ключа", "нормальный hit ratio", "только CDN", "GIL"], 0,
          "Lock/singleflight/early refresh."),
        q("distributed", "идемпотентный API важен при…",
          ["ретраях сети: повтор не должен дважды списать деньги", "только GET cache", "только UDP", "GIL"], 0,
          "Idempotency-Key, natural keys."),
        q("distributed", "at-least-once доставка значит…",
          ["сообщение может прийти >1 раза → нужна идемпотентность", "ровно один раз always", "never", "only batch"], 0,
          "Типично для очередей."),
        q("architecture", "CQRS идея…",
          ["разделить модели/пути чтения и записи", "запретить SQL", "только microservices", "убрать БД"], 0,
          "Сложные домены, разные нагрузки."),
        q("architecture", "hexagonal / ports & adapters…",
          ["ядро не зависит от деталей UI/БД", "всё в одном контроллере", "только monolith ban", "GIL architecture"], 0,
          "Тестируемость и замена адаптеров."),
        q("observability", "RED metrics для сервисов…",
          ["Rate, Errors, Duration", "RAM, EOF, Disk", "RPC, ETL, DDL", "only logs"], 0,
          "Базовый набор SLO."),
        q("observability", "structured logging лучше print тем, что…",
          ["поля JSON/ключ-значение → поиск/алерты", "всегда быстрее", "без timestamp", "без уровней"], 0,
          "Корреляция request_id и т.п."),
        q("performance", "когда __slots__ реально помогает?",
          ["много мелких объектов с фиксированными полями", "на одном singleton", "всегда на любом классе", "только dataclasses without fields"], 0,
          "Меньше памяти на __dict__."),
        q("performance", "интернирование строк / constant folding…",
          ["компилятор/рантайм могут переиспользовать объекты", "запрещены", "только в PyPy", "ломают =="], 0,
          "Не строй логику на is для строк/int."),
        q("C-API", "Py_LIMITED_API / stable ABI зачем?",
          ["бинарная совместимость расширений across versions", "убрать GIL", "faster pure python", "замена ctypes"], 0,
          "Меньше пересборок под каждый minor."),
        q("ctypes", "ctypes удобен для…",
          ["вызова C ABI без написания extension", "замены asyncio", "JIT", "typing"], 0,
          "Цена: unsafe, ручные типы, нет pythonic errors."),
        q("import", "sys.meta_path — это…",
          ["хуки поиска импортов (finders)", "только PYTHONPATH", "site-packages list only", "GIL hooks"], 0,
          "Можно ставить custom importers."),
        q("runtime", "sys.settrace / tracing…",
          ["отладка/coverage на уровне событий", "ускорение hot path", "GIL off", "async only"], 0,
          "Сильно замедляет; для prod — осторожно."),
        q("errors", "ExceptionGroup (3.11) нужен когда…",
          ["несколько ошибок параллельно (TaskGroup)", "вместо Exception always", "только SyntaxError", "warnings"], 0,
          "except* разбирает группу."),
        q("async", "cancellation в asyncio — это…",
          ["CancelledError в await-точке; finally должен убирать ресурсы", "мгновенный kill OS thread", "игнор finally", "GIL reset"], 0,
          "Пиши cancellation-safe cleanup."),
        q("design", "law of demeter грубо…",
          ["не цепочй obj.a.b.c — говори с соседями", "больше getters always", "god object ok", "no DTOs"], 0,
          "Меньше связности."),
        q("testing", "property-based (Hypothesis) ловит…",
          ["краевые случаи генерацией входов", "только UI", "только perf", "flake network always"], 0,
          "Дополнение к example-based тестам."),
        q("ci", "matrix builds проверяют…",
          ["несколько версий Python/OS", "только latest", "только mypy", "только black"], 0,
          "Совместимость пакета."),
        q("api", "pagination cursor vs offset?",
          ["cursor стабильнее при вставках; offset проще но «прыгает»", "offset always better", "cursor only SQL injection", "no difference"], 0,
          "Ленты/фиды — чаще cursor."),
        q("serialization", "msgpack/protobuf vs json?",
          ["компактнее/схема; json человекочитаем", "json всегда быстрее binary", "protobuf текстовый", "msgpack = pickle safe"], 0,
          "Выбор по контракту и экосистеме."),
        q("cache", "TTL + jitter зачем?",
          ["размазать истечения ключей во времени", "увеличить TTL forever", "отключить redis", "GIL"], 0,
          "Против синхронного stampede."),
        q("db", "connection pool exhaustion симптом…",
          ["запросы висят в ожидании свободного коннекта", "всегда CPU 100%", "только disk", "GIL"], 0,
          "Таймауты, утечки, длинные транзакции."),
        q("python", "tomllib (3.11+) читает…",
          ["TOML", "YAML", "INI only", "JSON5"], 0,
          "Стандартная библиотека для чтения TOML."),
        q("CPython", "specializing adaptive interpreter (3.11+)…",
          ["байткод адаптируется под типы в hot path", "удаляет GC", "отключает typing", "заменяет LLVM always"], 0,
          "Ускорение без смены языка."),
    ]


JUNIOR_W2 = build_junior()
MIDDLE_W2 = build_middle()
SENIOR_W2 = build_senior()


if __name__ == "__main__":
    print(len(JUNIOR_W2), len(MIDDLE_W2), len(SENIOR_W2), "total", len(JUNIOR_W2) + len(MIDDLE_W2) + len(SENIOR_W2))
