#!/usr/bin/env python3
"""Третья волна: классика собесов + «что выведет» по слабым темам."""
from __future__ import annotations


def q(topic, text, options, answer, explain, code=None):
    item = {
        "topic": topic,
        "q": text,
        "options": options,
        "answer": answer,
        "explain": explain,
    }
    if code:
        item["code"] = code
    return item


def build_junior() -> list[dict]:
    return [
        # ── условия / match ──
        q("условия", "Что выведет код?", ["yes", "no", "ошибка", "None"], 0,
          "Непустая строка — truthy, ветка if срабатывает.",
          code="print('yes' if 'x' else 'no')"),
        q("условия", "Что выведет код?", ["b", "a", "c", "ошибка"], 0,
          "Первое falsy — '', затем 'b' (truthy) → or возвращает 'b'.",
          code="print('' or 'b' or 'c')"),
        q("условия", "Что выведет код?", ["b", "a", "None", "ошибка"], 0,
          "and возвращает первый falsy или последнее значение. 'a' truthy → 'b'.",
          code="print('a' and 'b')"),
        q("условия", "Чем match/case (3.10+) отличается от цепочки if?",
          ["структурное сопоставление с паттернами", "только для int", "замена try/except", "только в asyncio"], 0,
          "Можно разбирать типы, последовательности, словари, с guard."),
        q("условия", "Что выведет код?", ["fail", "ok", "ошибка", "None"], 0,
          "x = 0 falsy → else-ветка тернарника.",
          code="x = 0\nprint('ok' if x else 'fail')"),

        # ── области / LEGB ──
        q("области", "Что выведет код?", ["2", "1", "ошибка", "None"], 0,
          "Без global присваивание x создаёт локальную; print читает локальную после x=2.",
          code="x = 1\ndef f():\n    x = 2\n    print(x)\nf()"),
        q("области", "Что будет?", ["UnboundLocalError", "1", "2", "SyntaxError"], 0,
          "Присваивание x делает x локальной на всю функцию; print(x) до присваивания — ошибка.",
          code="x = 1\ndef f():\n    print(x)\n    x = 2\nf()"),
        q("области", "nonlocal нужен чтобы…",
          ["писать во внешнюю (не global) область замыкания", "создать глобальную", "удалить переменную", "импортировать"], 0,
          "global — модуль; nonlocal — enclosing scope."),
        q("области", "Что выведет код?", ["[2, 2, 2]", "[0, 1, 2]", "ошибка", "[0, 0, 0]"], 0,
          "Классика: i захвачен по ссылке; к моменту вызова i уже 2.",
          code="funcs = [lambda: i for i in range(3)]\nprint([f() for f in funcs])"),
        q("области", "Как починить захват в lambda из цикла?",
          ["lambda i=i: i (default в момент создания)", "только global", "только nonlocal", "нельзя"], 0,
          "Default-аргумент фиксирует значение на каждой итерации."),

        # ── строки / f-string / bytes ──
        q("f-string", "Что выведет код?", ["name='Ada'", "Ada", "ошибка", "'name'"], 0,
          "Отладочный = в f-string (3.8+): показывает выражение и значение (с repr).",
          code="name = 'Ada'\nprint(f'{name=}')"),
        q("f-string", "Что выведет код?", ["3.142", "3.14", "3", "ошибка"], 0,
          ".3f — три знака после точки.",
          code="print(f'{3.14159:.3f}')"),
        q("строки", "Что выведет код?", ["['a', 'b', 'c']", "['a b c']", "'a|b|c'", "ошибка"], 0,
          "split('|') режет по каждому разделителю.",
          code="print('a|b|c'.split('|'))"),
        q("строки", "Что выведет код?", ["['a', 'b|c']", "['a', 'b', 'c']", "ошибка", "'a'"], 0,
          "maxsplit=1: максимум одно разрезание.",
          code="print('a|b|c'.split('|', 1))"),
        q("строки", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "isidentifier: допустимое имя переменной.",
          code="print('var_1'.isidentifier())"),
        q("байты", "Что выведет код?", ["b'hi'", "'hi'", "ошибка", "bytearray"], 0,
          "encode str → bytes.",
          code="print('hi'.encode())"),
        q("байты", "Что выведет код?", ["'hi'", "b'hi'", "ошибка", "list"], 0,
          "decode bytes → str.",
          code="print(b'hi'.decode())"),
        q("байты", "bytearray в отличие от bytes…",
          ["изменяемый", "неизменяемый", "это str", "только ASCII"], 0,
          "bytearray — mutable последовательность байт."),

        # ── списки / срезы / unpack ──
        q("срезы", "Что выведет код?", ["[1, 2, 3, 0]", "[1, 2, 3]", "[1, 2]", "ошибка"], 0,
          "Присвоение срезу заменяет кусок: [0,0,0] → [1,2,3,0].",
          code="a = [0, 0, 0]\na[0:2] = [1, 2, 3]\nprint(a)"),
        q("срезы", "Что выведет код?", ["[1, 3, 5]", "[1, 2, 3, 4, 5]", "[0, 2, 4]", "ошибка"], 0,
          "Шаг 2 с индекса 1: 1,3,5.",
          code="print([0, 1, 2, 3, 4, 5][1::2])"),
        q("unpack", "Что выведет код?", ["1 4 [2, 3]", "1 2 [3, 4]", "ошибка", "1 2 3 4"], 0,
          "a=1, c=4, *b собирает середину [2, 3].",
          code="a, *b, c = [1, 2, 3, 4]\nprint(a, c, b)"),
        q("unpack", "Что будет?", ["ValueError", "[1, 2]", "1", "None"], 0,
          "Слишком много значений для a, b.",
          code="a, b = [1, 2, 3]"),
        q("списки", "Что выведет код?", ["[1, 2, 3, 4]", "[1, 2]", "None", "ошибка"], 0,
          "+= для list — extend in-place.",
          code="a = [1, 2]\na += [3, 4]\nprint(a)"),
        q("списки", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "clear очищает тот же объект; b ссылается на него → [].",
          code="a = [1, 2]\nb = a\na.clear()\nprint(b == [])"),
        q("кортежи", "Что выведет код?", ["(1, 2, 3)", "ошибка", "[1, 2, 3]", "(1, 2)"], 0,
          "Конкатенация кортежей создаёт новый tuple.",
          code="print((1, 2) + (3,))"),
        q("кортежи", "Почему (1) это не кортеж?",
          ["нужна запятая: (1,)", "скобки запрещены", "только []", "нужен tuple(1)"], 0,
          "Скобки группируют выражение; кортеж создаёт запятая."),

        # ── словари / множества ──
        q("словари", "Что выведет код?", ["2", "1", "ошибка", "None"], 0,
          "Повторный ключ: побеждает последнее значение.",
          code="print({'a': 1, 'a': 2}['a'])"),
        q("словари", "Что выведет код?", ["dict_items([('a', 1)])", "[('a', 1)]", "ошибка", "['a']"], 0,
          "items() — view; print показывает dict_items(...).",
          code="print({'a': 1}.items())"),
        q("словари", "Что выведет код?", ["{'a': 1, 'b': 2}", "{'b': 2}", "ошибка", "{'a': 1}"], 0,
          "| объединяет; справа перезаписывает ключи.",
          code="print({'a': 1} | {'b': 2})"),
        q("словари", "d.setdefault('k', []).append(1) — что в d['k']?",
          ["[1]", "1", "None", "ошибка"], 0,
          "setdefault кладёт [] если ключа нет и возвращает его; append мутирует."),
        q("множества", "Что выведет код?", ["{1, 2, 3}", "{1, 2}", "ошибка", "[1, 2, 3]"], 0,
          "update добавляет элементы из итерируемого.",
          code="s = {1, 2}\ns.update([2, 3])\nprint(s)"),
        q("множества", "Что будет?", ["TypeError", "{[1]}", "{1}", "frozenset"], 0,
          "list не hashable — нельзя положить в set.",
          code="print({[1]})"),
        q("множества", "frozenset чем полезен?",
          ["hashable → ключ dict / элемент set", "быстрее list", "изменяемый", "сортирует"], 0,
          "Неизменяемое множество."),

        # ── циклы / comprehension ──
        q("циклы", "Что выведет код?", ["0 1 2 done", "0 1 2", "done", "ошибка"], 0,
          "for/else: else если не было break.",
          code="for i in range(3):\n    print(i, end=' ')\nelse:\n    print('done')"),
        q("циклы", "Что выведет код?", ["0 1", "0 1 done", "done", "ошибка"], 0,
          "break пропускает else у for.",
          code="for i in range(3):\n    if i == 2:\n        break\n    print(i, end=' ')\nelse:\n    print('done')"),
        q("dictcomp", "Что выведет код?", ["{1: 1, 2: 4}", "{1, 4}", "[1, 4]", "ошибка"], 0,
          "Dict comprehension: ключ → квадрат.",
          code="print({x: x * x for x in (1, 2)})"),
        q("listcomp", "Что выведет код?", ["[1, 3]", "[0, 1, 2, 3]", "[1, 2, 3]", "ошибка"], 0,
          "Фильтр if x % 2.",
          code="print([x for x in range(4) if x % 2])"),
        q("listcomp", "Разница [ ] и ( ) в comprehension?",
          ["list vs generator expression", "одинаково", "() — tuple comp", "ошибка синтаксиса"], 0,
          "Круглые скобки — ленивый generator expression."),

        # ── функции / ошибки / ООП ──
        q("функции", "Что выведет код?", ["None", "[1]", "ошибка", "[]"], 0,
          "append возвращает None; print этого None.",
          code="a = []\nprint(a.append(1))"),
        q("функции", "Что выведет код?", ["[1, 1]", "[1]", "ошибка", "[]"], 0,
          "Mutable default общий для вызовов: после двух f() список [1, 1].",
          code="def f(x=[]):\n    x.append(1)\n    return x\nf()\nprint(f())"),
        q("функции", "Как правильно default для списка?",
          ["def f(x=None): x = [] if x is None else x", "def f(x=[]):", "def f(x=list):", "нельзя"], 0,
          "None-sentinel — стандартный паттерн."),
        q("ошибки", "IndexError vs KeyError?",
          ["индекс последовательности vs ключ dict", "одно и то же", "только для set", "только строки"], 0,
          "Разные типы контейнеров — разные исключения."),
        q("ошибки", "Что выведет код?", ["caught", "boom", "ошибка без вывода", "None"], 0,
          "except Exception ловит ValueError.",
          code="try:\n    raise ValueError('boom')\nexcept Exception:\n    print('caught')"),
        q("ошибки", "except: без типа ловит…",
          ["включая KeyboardInterrupt/SystemExit (BaseException)", "только Exception", "только ValueError", "ничего"], 0,
          "Голый except опасен — лучше except Exception."),
        q("ООП", "Что выведет код?", ["A", "B", "ошибка", "None"], 0,
          "Метод ищется в классе экземпляра: B.hello → A.hello через MRO.",
          code="class A:\n    def hello(self):\n        return 'A'\nclass B(A):\n    pass\nprint(B().hello())"),
        q("ООП", "__str__ vs __repr__?",
          ["str — для пользователя; repr — однозначное/отладочное", "одинаковы", "str только для print чисел", "repr запрещён"], 0,
          "print использует str; контейнеры — repr элементов."),
        q("ООП", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
          "issubclass проверяет наследование классов.",
          code="print(issubclass(bool, int))"),

        # ── встроенные / инструменты ──
        q("встроенные", "Что выведет код?", ["[(1, 'a'), (2, 'b')]", "[(1, 'a'), (2, 'b'), (3, None)]", "ошибка", "[1, 2, 3, 'a', 'b']"], 0,
          "zip обрезает по короткой последовательности → две пары.",
          code="print(list(zip([1, 2, 3], ['a', 'b'])))"),
        q("enumerate", "Что выведет код?", ["[(1, 'a'), (2, 'b')]", "[(0, 'a'), (1, 'b')]", "ошибка", "['a', 'b']"], 0,
          "start=1 сдвигает индексы.",
          code="print(list(enumerate(['a', 'b'], start=1)))"),
        q("ввод", "int(input()) упадёт если…",
          ["ввели не число", "ввели '0'", "ввели отрицательное", "всегда ок"], 0,
          "ValueError на нечисловой строке."),
        q("JSON", "json.loads('{\"a\": 1}') вернёт…",
          ["dict", "str", "JSON object type", "tuple"], 0,
          "loads парсит строку JSON в объекты Python."),
        q("JSON", "Ключи в JSON объекте после loads — это…",
          ["str", "любой hashable", "bytes", "int всегда"], 0,
          "В JSON ключи — строки; в Python dict после loads тоже str."),
        q("pep8", "Длина строки по PEP 8 (мягкий лимит)?",
          ["79 (или 99 в команде)", "120 обязательно", "без лимита", "40"], 0,
          "Классика 79; многие команды ставят 88–100."),
        q("модули", "import math; math.pi — pi это…",
          ["атрибут модуля", "ключевое слово", "builtin", "класс"], 0,
          "Имена из модуля доступны через точку."),
        q("venv", "После создания venv обычно делают…",
          ["activate + pip install", "только copy site-packages", "перезагрузку ОС", "pip freeze без activate"], 0,
          "Активация подставляет интерпретатор окружения."),
    ]


def build_middle() -> list[dict]:
    return [
        # ── декораторы / замыкания ──
        q("декораторы", "Что делает @functools.wraps(f)?",
          ["копирует __name__/__doc__ с обёрнутой функции", "ускоряет вызов", "делает async", "убирает GIL"], 0,
          "Иначе инспекция видит wrapper."),
        q("декораторы", "Декоратор с аргументами — это…",
          ["фабрика: вызывается сразу и возвращает декоратор", "обычный @f", "только class decorator", "запрещено"], 0,
          "@deco(x) сначала вызывает deco(x)."),
        q("замыкания", "Что выведет код?", ["10", "0", "ошибка", "None"], 0,
          "nonlocal n позволяет менять enclosing переменную.",
          code="def make():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 10\n        return n\n    return inc\nprint(make()())"),
        q("closures", "cell в замыкании хранит…",
          ["ссылку на переменную enclosing scope", "копию int всегда", "только globals", "байткод"], 0,
          "Поздний lookup — причина лямбда-в-цикле."),
        q("декораторы", "Что выведет код (по порядку)?", ["before, затем 1", "только 1", "ошибка", "только before"], 0,
          "Обёртка печатает before, затем возвращает 1 — print(f()) печатает 1.",
          code="def deco(f):\n    def wrap():\n        print('before')\n        return f()\n    return wrap\n@deco\ndef f():\n    return 1\nprint(f())"),

        # ── генераторы / итераторы ──
        q("генераторы", "Что выведет код?", ["1 2", "1 2 3", "ошибка", "None"], 0,
          "Два next() забирают оба элемента генератора.",
          code="g = (x for x in [1, 2])\nprint(next(g), next(g))"),
        q("генераторы", "yield from делегирует…",
          ["итерацию/yield во вложенный итератор/генератор", "только return", "в другой процесс", "в C API"], 0,
          "Также пробрасывает send/throw."),
        q("генераторы", "Что вернёт gen.send(x) до первого yield?",
          ["нужно сначала next()/send(None)", "сразу x", "None", "ошибка всегда"], 0,
          "Генератор должен дойти до yield."),
        q("итераторы", "iter(callable, sentinel) вызывает callable пока…",
          ["результат != sentinel", "пока True", "один раз", "бесконечно без sentinel"], 0,
          "Классика: iter(f.readline, '')."),
        q("generators", "Что выведет код?", ["[1]", "[1, 0]", "ошибка", "[0]"], 0,
          "return в генераторе становится StopIteration.value; list() его не включает — только yield.",
          code="def g():\n    yield 1\n    return 0\nprint(list(g()))"),

        # ── context / magic ──
        q("context", "__enter__ возвращает…",
          ["то, что попадает в as", "всегда None", "только self", "файл"], 0,
          "with CM() as x: x = результат __enter__."),
        q("context", "contextlib.contextmanager превращает…",
          ["генератор с одним yield в CM", "класс в функцию", "async в sync", "dict в with"], 0,
          "Код до yield — enter; после — exit."),
        q("магические", "__len__ должен возвращать…",
          ["int >= 0", "любой float", "str", "bool только"], 0,
          "Иначе TypeError у len()."),
        q("магические", "Что вызовет a + b?",
          ["a.__add__(b) или b.__radd__(a)", "только __iadd__", "len(a)", "hash(a)"], 0,
          "Отражённые методы для правого операнда."),
        q("property", "@property.setter нужен чтобы…",
          ["разрешить присваивание атрибуту-property", "сделать classmethod", "удалить атрибут", "ускорить"], 0,
          "Иначе AttributeError: can't set attribute."),
        q("classmethod", "classmethod получает первым аргументом…",
          ["класс (cls), не экземпляр", "self", "модуль", "metaclass всегда"], 0,
          "Удобно для альтернативных конструкторов."),
        q("staticmethod", "staticmethod отличается тем, что…",
          ["нет авто-self/cls — обычная функция в классе", "всегда виртуальный", "только в ABC", "быстрее C"], 0,
          "Не получает ни экземпляр, ни класс."),

        # ── typing / dataclasses ──
        q("typing", "list[int] в runtime (3.9+) — это…",
          ["generic alias; isinstance ограниченно", "точный runtime gate всегда", "удаляется", "только mypy"], 0,
          "Аннотации не проверяются CPython сам по себе."),
        q("typing", "TypeVar(bound=...) ограничивает…",
          ["верхнюю границу допустимых типов", "только литералы", "длину списка", "GIL"], 0,
          "T должен быть subtype bound."),
        q("typing", "Protocol (structural) vs ABC?",
          ["Protocol — утиная типизация; ABC — номинальная", "одно и то же", "Protocol только runtime", "ABC только stubs"], 0,
          "typing.Protocol / runtime_checkable."),
        q("dataclasses", "Что даёт frozen=True?",
          ["неизменяемые экземпляры (приблизительно)", "быстрее всегда", "slots автоматически до 3.9", "JSON"], 0,
          "Присваивание полей → FrozenInstanceError."),
        q("dataclasses", "field(default_factory=list) зачем?",
          ["новый list на каждый экземпляр", "общий list", "запретить поле", "только для str"], 0,
          "Аналог осторожности с mutable default."),
        q("dataclasses", "order=True добавляет…",
          ["сравнение по полям (__lt__ и др.)", "сортировку dict", "hash всегда", "slots"], 0,
          "Нужен eq=True (по умолчанию)."),
        q("enum", "Enum члены сравниваются…",
          ["по идентичности/значению члена, не как «сырые» int без mixin", "всегда как int", "только по имени str", "нельзя"], 0,
          "IntEnum — отдельный случай, совместим с int."),
        q("match", "case [x, *rest]: матчит…",
          ["последовательность ≥1 с хвостом", "только list длины 2", "dict", "set"], 0,
          "Sequence pattern."),

        # ── concurrency / asyncio ──
        q("GIL", "GIL мешает…",
          ["параллельному CPU-коду в потоках CPython", "любому I/O", "multiprocessing", "asyncio sleep"], 0,
          "I/O и C-extensions могут отпускать GIL."),
        q("threading", "Lock vs RLock?",
          ["RLock можно захватывать тем же потоком повторно", "Lock быстрее всегда и reentrant", "одно и то же", "RLock только async"], 0,
          "Обычный Lock — deadlock при повторном acquire."),
        q("multiprocessing", "Queue между процессами…",
          ["сериализует объекты (pickle)", "делит память без копий всегда", "только потоки", "GIL queue"], 0,
          "Передача — через pickle/pipes."),
        q("asyncio", "create_task vs await coro напрямую?",
          ["task планирует конкурентно; await — последовательно", "одинаково", "create_task блокирует", "await запрещён"], 0,
          "Task позволяет параллелить await-точки."),
        q("asyncio", "Что будет при необработанном исключении в Task?",
          ["логируется при GC task (и в 3.11+ лучше видно)", "тихо глотается навсегда", "роняет процесс всегда", "чинит само"], 0,
          "Храни ссылку / await / callbacks."),
        q("asyncio", "async with vs обычный with для lock?",
          ["нужен async CM с __aenter__/__aexit__", "можно смешивать свободно", "with быстрее", "запрещено"], 0,
          "asyncio.Lock — async context manager."),
        q("async", "gather(..., return_exceptions=True)…",
          ["кладёт исключения в результаты вместо raise", "игнорит все задачи", "отменяет всегда", "только sync"], 0,
          "Удобно собрать частичные успехи."),

        # ── stdlib / collections ──
        q("collections", "deque.appendleft — амортизированно…",
          ["O(1)", "O(n)", "O(log n)", "O(n²)"], 0,
          "Двусторонняя очередь."),
        q("collections", "Counter.most_common(2) вернёт…",
          ["список пар (элемент, счёт) топ-2", "только ключи", "dict", "set"], 0,
          "По убыванию частоты."),
        q("collections", "defaultdict(list): d['k'].append(1) — если ключа не было?",
          ["создаст [] и append", "KeyError", "NoneType error", "игнор"], 0,
          "default_factory вызывается."),
        q("itertools", "islice(it, 2, 5) берёт…",
          ["элементы с 2 по 4 (как range)", "первые 5", "с 2 до конца", "только 2 и 5"], 0,
          "Ленивый срез итератора."),
        q("itertools", "groupby требует…",
          ["чтобы одинаковые ключи шли подряд (часто sort заранее)", "hashable keys only set", "list всегда", "async"], 0,
          "Иначе группы разобьются."),
        q("functools", "lru_cache(maxsize=None) это…",
          ["безлимитный кэш (осторожно с памятью)", "без кэша", "TTL cache", "disk cache"], 0,
          "Эквивалент unbounded memoization."),
        q("functools", "partial(f, 1)(2) эквивалентно…",
          ["f(1, 2)", "f(2, 1)", "f(1)", "f()"], 0,
          "Фиксирует позиционные/keyword аргументы."),
        q("pathlib", "Path('a') / 'b' / 'c' даст…",
          ["Path с платформенными разделителями", "строку 'a/b/c' всегда", "ошибку", "bytes"], 0,
          "Оператор / у Path."),
        q("regex", "re.search vs re.match?",
          ["search — в любом месте; match — с начала строки", "одинаково", "match быстрее всегда", "search только bytes"], 0,
          "Ещё есть fullmatch."),
        q("logging", "Почему logger = logging.getLogger(__name__)?",
          ["иерархия логгеров по модулю", "обязательный синтаксис", "быстрее print", "отключает root"], 0,
          "Удобно фильтровать по имени пакета."),

        # ── тесты / веб / sql ──
        q("тесты", "pytest fixture с scope='module'…",
          ["один раз на модуль тестов", "на каждый assert", "на весь CI", "только class"], 0,
          "Экономия дорогой подготовки."),
        q("тесты", "monkeypatch / mock патчат…",
          ["атрибуты/окружение на время теста", "продакшен БД", "GIL", "байткод"], 0,
          "Изоляция побочных эффектов."),
        q("mock", "assert_called_once_with(...) проверяет…",
          ["ровно один вызов с аргументами", "любое число вызовов", "только тип", "время"], 0,
          "Из unittest.mock."),
        q("HTTP", "идемпотентный HTTP-метод пример…",
          ["GET / PUT (в идеале)", "POST всегда", "только CONNECT", "TRACE обязателен"], 0,
          "Повтор не должен менять состояние (семантика)."),
        q("FastAPI", "Depends() нужен для…",
          ["внедрения зависимостей (DI) в эндпоинты", "SQL only", "GIL", "замены pydantic"], 0,
          "Переиспользование auth/db session."),
        q("SQL", "N+1 проблема — это…",
          ["1 запрос списка + N запросов на связанные сущности", "один огромный JOIN всегда bad", "только NoSQL", "индекс"], 0,
          "Лечится join/eager load/IN."),
        q("copy", "copy.copy vs deepcopy?",
          ["shallow копирует верх; deep — рекурсивно", "одинаково", "copy быстрее deep всегда и безопаснее", "deepcopy только list"], 0,
          "Вложенные мутабельные объекты."),
        q("weakref", "WeakValueDictionary забывает значение когда…",
          ["не осталось сильных ссылок на объект", "всегда через 1с", "при hash collision", "никогда"], 0,
          "Кэши без удержания объектов."),
        q("ABC", "@abstractmethod гарантирует…",
          ["нельзя инстанцировать подкласс без реализации", "runtime скорость", "GIL off", "pickle"], 0,
          "Пока есть абстрактные методы — TypeError."),
        q("дескрипторы", "__get__/__set__/__delete__ — это…",
          ["протокол дескрипторов (property так устроен)", "только metaclass", "GIL hooks", "async only"], 0,
          "Data vs non-data descriptors."),
    ]


def build_senior() -> list[dict]:
    return [
        # ── CPython / память ──
        q("CPython", "Что такое PyObject заголовок (упрощённо)?",
          ["refcount + указатель на тип (и ещё поля)", "только данные без типа", "только GIL token", "только hash"], 0,
          "Любой объект в CPython — PyObject*."),
        q("CPython", "interning маленьких int (−5…256) зачем?",
          ["переиспользование объектов, меньше аллокаций", "обязательная математика", "безопасность", "убрать =="], 0,
          "Поэтому is для таких int может «случайно» работать."),
        q("память", "pymalloc — это…",
          ["аренааллокатор мелких объектов CPython", "OS malloc замена полностью", "GC алгоритм", "swap"], 0,
          "Оптимизация частых мелких аллокаций."),
        q("память", "цикл ссылок A→B→A собирает…",
          ["generational GC (detect cycles)", "только refcount", "never", "OS OOM killer only"], 0,
          "refcount сам цикл не разорвёт."),
        q("байткод", "dis.dis(f) показывает…",
          ["байткод функции", "машинный код CPU", "LLVM IR always", "AST only"], 0,
          "Полезно понимать оптимизации/ловушки."),
        q("байткод", "LOAD_FAST vs LOAD_GLOBAL по стоимости?",
          ["локальные быстрее глобальных/builtins lookup", "одинаково", "global быстрее", "только PyPy"], 0,
          "Локальные — массив быстрого доступа."),
        q("import", "sys.modules кэширует…",
          ["уже загруженные модули по имени", "только bytecode файлы", "pip packages", "типы"], 0,
          "Повторный import берёт из кэша."),
        q("import", "circular import типичный симптом…",
          ["AttributeError: partially initialized module", "SyntaxError всегда", "GIL deadlock only", "segfault"], 0,
          "Лечится локальными import / перестройкой зависимостей."),

        # ── метаклассы / дескрипторы ──
        q("метаклассы", "type(name, bases, namespace) создаёт…",
          ["новый класс", "экземпляр only", "модуль", "функцию"], 0,
          "class statement — синтаксический сахар над этим."),
        q("метаклассы", "__init_subclass__ вызывается…",
          ["при создании подкласса", "при import любого модуля", "при del", "только metaclass"], 0,
          "Хуки регистрации без своего metaclass."),
        q("метаклассы", "__set_name__ у дескриптора…",
          ["узнаёт имя атрибута в классе-владельце", "ставит __name__ функции", "GIL name", "pickle name"], 0,
          "PEP 487."),
        q("дескрипторы", "data descriptor (с __set__) побеждает…",
          ["instance __dict__", "всегда non-data", "только slots", "ничего"], 0,
          "Порядок поиска атрибутов важен."),
        q("typing", "ParamSpec / Concatenate нужны для…",
          ["типизации декораторов, сохраняющих сигнатуру", "только dataclasses", "SQL", "GIL"], 0,
          "PEP 612."),
        q("typing", "TypeGuard / TypeIs помогают…",
          ["сузить тип после user-defined проверки", "ускорить runtime", "заменить isinstance ban", "GC"], 0,
          "Для чекеров типов."),

        # ── concurrency / async advanced ──
        q("concurrency", "free-threaded CPython (3.13+) меняет…",
          ["опциональная сборка без GIL", "удаляет потоки", "запрещает multiprocessing", "только asyncio"], 0,
          "Новая модель памяти/потокобезопасности расширений."),
        q("asyncio", "TaskGroup (3.11) при ошибке в задаче…",
          ["отменяет siblings и поднимает ExceptionGroup", "глотает", "убивает процесс", "игнорит cancel"], 0,
          "Структурная конкурентность."),
        q("asyncio", "почему нельзя вызывать blocking time.sleep в корутине?",
          ["блокирует event loop целиком", "ломает только эту task", "запрещено синтаксисом", "нужен GIL off"], 0,
          "asyncio.sleep / to_thread / executor."),
        q("multiprocessing", "fork без exec на macOS/spawn — риск…",
          ["небезопасное состояние lock/threads после fork", "только медленнее", "нет риска", "только Windows"], 0,
          "Поэтому default start method часто spawn."),
        q("signals", "обработчик сигнала в CPython выполняется…",
          ["между байткод-инструкциями основного потока", "мгновенно в любом потоке", "только в C", "в GC"], 0,
          "Ограничения на то, что безопасно делать в handler."),

        # ── security / api ──
        q("security", "pickle.loads из недоверенного источника?",
          ["RCE-риск — нельзя", "безопасно как json", "только DoS", "ok с HTTPS"], 0,
          "pickle выполняет код при десериализации."),
        q("security", "sql injection лечится…",
          ["параметризованными запросами / ORM bind", "экранированием вручную через replace", "uppercase SQL", "GIL"], 0,
          "Никогда не склеивай SQL строками с user input."),
        q("security", "timing attack на сравнение секретов — защита?",
          ["hmac.compare_digest / secrets.compare_digest", "обычный ==", "len() check only", "hash() =="], 0,
          "Константное по времени сравнение."),
        q("security", "SSRF — это…",
          ["сервер ходит по URL от пользователя во внутреннюю сеть", "XSS в браузере", "SQL inject", "CSRF form"], 0,
          "Валидируй/проксируй исходящие запросы."),
        q("api", "идемпотентный ключ в платежах зачем?",
          ["безопасный retry без двойного списания", "ускорение CPU", "шифрование", "пагинация"], 0,
          "Клиент присылает уникальный ключ операции."),
        q("api", "rate limit 429 — клиенту стоит…",
          ["backoff + Retry-After", "долбить без паузы", "сменить на POST", "игнор"], 0,
          "Иначе бан/шторм."),
        q("api", "проблема lost update при concurrent PUT?",
          ["нужны ETag/version / if-match / транзакции", "только HTTPS", "больше CPU", "pickle"], 0,
          "Оптимистичные блокировки."),

        # ── architecture / data ──
        q("architecture", "outbox pattern решает…",
          ["атомарность записи в БД + публикации события", "только кэш", "GIL", "UI state"], 0,
          "Событие пишется в outbox-таблицу в той же транзакции."),
        q("architecture", "saga vs 2PC?",
          ["saga — локальные транзакции + компенсации; 2PC — распределённый commit", "одно и то же", "saga только monolith", "2PC без координатора"], 0,
          "В микросервисах чаще saga."),
        q("architecture", "backpressure означает…",
          ["потребитель сигналит замедлить производителя", "больше RAM always", "drop all metrics", "только TCP window в Python"], 0,
          "Очереди, async streams, HTTP/2 windows…"),
        q("distributed", "exactly-once в реальности часто…",
          ["at-least-once + идемпотентность на приёме", "бесплатно в любой очереди", "только UDP", "GIL guarantee"], 0,
          "Энд-ту-энд exactly-once дорог/условен."),
        q("distributed", "clock skew ломает…",
          ["логику по wall-clock без NTP/logical clocks", "только SSD", "только GIL", "hash()"], 0,
          "Лучше monotonic / version vectors где нужно."),
        q("db", "READ COMMITTED не защищает от…",
          ["non-repeatable / phantom (в зависимости от СУБД)", "грязного чтения чужих незакоммиченных? (обычно защищает)", "всех аномалий serializable", "сети"], 0,
          "Знай изоляции своей БД."),
        q("db", "covering index — это…",
          ["индекс, из которого можно ответить без обращения к таблице", "полный table scan", "только PK", "foreign key"], 0,
          "Index-only scan."),
        q("cache", "stampede / thundering herd — это…",
          ["масса запросов одновременно пересчитывает один ключ", "OOM от одного ключа", "DNS fail", "GIL"], 0,
          "Lock/singleflight, soft TTL, jitter."),
        q("cache", "negative caching кэширует…",
          ["факт отсутствия (404/miss) на короткое время", "только hits", "пароли", "байткод"], 0,
          "Против повторных дорогих miss."),
        q("serialization", "почему protobuf/schema evolution важны?",
          ["совместимость клиентов при изменении полей", "красивый JSON", "GIL", "только скорость"], 0,
          "Правила reserved/optional/default."),

        # ── observability / packaging / native ──
        q("observability", "trace vs log vs metric?",
          ["trace — путь запроса; log — события; metric — агрегаты", "одно и то же", "metric = stacktrace", "log заменяет SLO"], 0,
          "Три столпа observability."),
        q("observability", "cardinality взрыв в метках — риск…",
          ["миллионы time series → дорого/медленно", "только prettier graphs", "безопасность", "GIL"], 0,
          "Не клади user_id в label Prometheus без нужды."),
        q("packaging", "pyproject.toml [project] — стандарт…",
          ["метаданные/зависимости пакета (PEP 621)", "только poetry lock", "замена setuptools ban", "только tox"], 0,
          "Единая точка конфигурации."),
        q("packaging", "abi3 / stable ABI wheels зачем?",
          ["один wheel на несколько версий CPython", "быстрее pure python", "убрать mypy", "Docker only"], 0,
          "Limited API."),
        q("C-API", "PyErr_SetString + return NULL — паттерн…",
          ["сообщить об ошибке в Python из C", "успех", "отключить GC", "release GIL"], 0,
          "Вызывающая сторона проверяет ошибку."),
        q("ctypes", "главный риск ctypes?",
          ["segfault/UB при неверных типах/lifetime", "только медленно", "нет риска", "ломает pip"], 0,
          "Нет защиты памяти Python."),
        q("performance", "когда профилировать преждевременно — плохо; но первый инструмент?",
          ["cProfile / py-spy / scalene — по задаче", "сразу переписать на C", "отключить GC навсегда", "больше print"], 0,
          "Измеряй, потом оптимизируй."),
        q("performance", "vectorization (numpy) выигрывает за счёт…",
          ["C-циклов без GIL-питона на элемент", "большего числа потоков Python always", "pickle", "f-string"], 0,
          "Меньше интерпретации байткода."),
        q("testing", "mutation testing проверяет…",
          ["ловят ли тесты намеренно испорченный код", "только coverage %", "perf", "типы"], 0,
          "Дополнение к coverage."),
        q("testing", "contract / consumer-driven tests полезны когда…",
          ["много сервисов и независимые релизы", "один монолит без API", "только UI", "GIL"], 0,
          "Фиксируют ожидания потребителя API."),
        q("design", "anti-corruption layer — это…",
          ["адаптер, изолирующий домен от чужой модели/legacy", "firewall OS", "GIL wrapper", "кэш Redis"], 0,
          "DDD: не протекает внешняя модель."),
        q("design", "feature flag риск без дисциплины?",
          ["мертвый код, комбинаторный взрыв состояний", "только ускорение", "бесплатная A/B без цены", "безопасность always"], 0,
          "Нужны TTL флагов и уборка."),
        q("errors", "except* (3.11) работает с…",
          ["ExceptionGroup", "любым Exception одинаково как except", "только BaseExceptionGroup ban", "warnings"], 0,
          "Распаковка групп ошибок."),
        q("python", "PEP 703 связан с…",
          ["делает GIL опциональным", "pattern matching", "tomllib", "dataclasses"], 0,
          "Free-threading initiative."),
        q("runtime", "faulthandler полезен чтобы…",
          ["дампить трейсбеки при крашах/сигналах", "ускорить код", "типизировать", "убрать GC"], 0,
          "Отладка зависаний и фатальных ошибок."),
    ]


JUNIOR_W3 = build_junior()
MIDDLE_W3 = build_middle()
SENIOR_W3 = build_senior()


if __name__ == "__main__":
    print(len(JUNIOR_W3), len(MIDDLE_W3), len(SENIOR_W3), "total", len(JUNIOR_W3) + len(MIDDLE_W3) + len(SENIOR_W3))
