#!/usr/bin/env python3
"""Code-output interview questions («что выведет?»)."""


from bank.utils import q


CODE_JUNIOR = [
    q("встроенные", "Что выведет код?", ["[0, 1, 4]", "[1, 4, 9]", "[0, 1, 2]", "ошибка"], 0,
      "x*x для 0,1,2.", code="print([x * x for x in range(3)])"),
    q("строки", "Что выведет код?", ["cba", "abc", "a", "ошибка"], 0,
      "Срез с шагом -1.", code="print('abc'[::-1])"),
    q("списки", "Что выведет код?", ["[1, 2, 3, 4]", "[1, 2, [3, 4]]", "ошибка", "None"], 0,
      "extend разворачивает.", code="a = [1, 2]\na.extend([3, 4])\nprint(a)"),
    q("списки", "Что выведет код?", ["[1, 2, [3, 4]]", "[1, 2, 3, 4]", "ошибка", "None"], 0,
      "append добавляет один объект.", code="a = [1, 2]\na.append([3, 4])\nprint(a)"),
    q("словари", "Что выведет код?", ["0", "None", "KeyError", "1"], 0,
      "get с default.", code="print({'a': 1}.get('b', 0))"),
    q("операторы", "Что выведет код?", ["8", "6", "9", "5"], 0,
      "2**3.", code="print(2 ** 3)"),
    q("операторы", "Что выведет код?", ["3", "3.5", "4", "2"], 0,
      "Целочисленное деление.", code="print(7 // 2)"),
    q("сравнения", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
      "[] == False → False.", code="print([] == False)"),
    q("сравнения", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
      "bool([]) ложен.", code="print(bool([]))"),
    q("функции", "Что выведет код?", ["None", "0", "ошибка", "''"], 0,
      "Без return → None.", code="def f():\n    pass\nprint(f())"),
    q("копирование", "Что выведет код?", ["[1]", "[]", "ошибка", "[0]"], 0,
      "Одна ссылка.", code="a = b = []\na.append(1)\nprint(b)"),
    q("копирование", "Что выведет код?", ["[]", "[1]", "ошибка", "None"], 0,
      "Срез — новый список.", code="a = []\nb = a[:]\na.append(1)\nprint(b)"),
    q("циклы", "Что выведет код?", ["0 1 2", "1 2 3", "0 1 2 3", "ошибка"], 0,
      "range(3).", code="print(*range(3))"),
    q("строки", "Что выведет код?", ["Hi Ann", "Hi {name}", "ошибка", "Hi name"], 0,
      "f-string.", code="name = 'Ann'\nprint(f'Hi {name}')"),
    q("кортежи", "Что выведет код?", ["1", "(1)", "ошибка", "0"], 0,
      "Кортеж из одного элемента.", code="print(len((1,)))"),
    q("множества", "Что выведет код?", ["{1, 2}", "{1, 1, 2}", "[1, 1, 2]", "ошибка"], 0,
      "Уникальность.", code="print(set([1, 1, 2]))"),
    q("ошибки", "Что произойдёт?", ["ZeroDivisionError", "ValueError", "TypeError", "напечатает inf"], 0,
      "Деление на ноль.", code="print(1 / 0)"),
    q("ошибки", "Что произойдёт?", ["TypeError", "ValueError", "OK 'a1'", "SyntaxError"], 0,
      "str + int.", code="print('a' + 1)"),
    q("встроенные", "Что выведет код?", ["[(0, 'a'), (1, 'b')]", "[(1, 'a'), (2, 'b')]", "ошибка", "['a','b']"], 0,
      "enumerate с 0.", code="print(list(enumerate('ab')))"),
    q("zip", "Что выведет код?", ["[(1, 'a'), (2, 'b')]", "[1, 2, 'a', 'b']", "ошибка", "[(1,), ('a',)]"], 0,
      "zip попарно.", code="print(list(zip([1, 2], ['a', 'b'])))"),
    q("any", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
      "Все falsy.", code="print(any([0, '', False]))"),
    q("all", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
      "Пустой all → True.", code="print(all([]))"),
    q("срезы", "Что выведет код?", ["[2, 3]", "[1, 2]", "[2]", "[1, 2, 3, 4]"], 0,
      "Срез 1:3.", code="print([1, 2, 3, 4][1:3])"),
    q("операторы", "Что выведет код?", ["ok", "0", "False", "ошибка"], 0,
      "or возвращает операнд.", code="print(0 or 'ok')"),
    q("операторы", "Что выведет код?", ["0", "1", "True", "ошибка"], 0,
      "and возвращает первый ложный.", code="print(0 and 1)"),
    q("bool", "Что выведет код?", ["2", "True", "ошибка", "1"], 0,
      "True+True.", code="print(True + True)"),
    q("типы", "Что выведет код?", ["bool", "<class 'bool'> как тип bool", "int", "TrueType"], 0,
      "type(True) is bool — в print: <class 'bool'>, смысл — bool.",
      code="print(type(True).__name__)"),
    q("listcomp", "Что выведет код?", ["[0, 2, 4]", "[1, 3]", "[0,1,2,3,4]", "ошибка"], 0,
      "Чётные.", code="print([i for i in range(5) if i % 2 == 0])"),
    q("unpack", "Что выведет код?", ["[2, 3]", "2", "[1, 2, 3]", "ошибка"], 0,
      "Star unpacking.", code="a, *b = [1, 2, 3]\nprint(b)"),
    q("dict", "Что выведет код?", ["['a', 'b']", "[1, 2]", "ошибка", "dict_keys"], 0,
      "list(dict) — ключи.", code="print(list({'a': 1, 'b': 2}))"),
    q("строки", "Что выведет код?", ["['a', 'b,c']", "['a', 'b', 'c']", "ошибка", "'a'"], 0,
      "maxsplit=1.", code="print('a,b,c'.split(',', 1))"),
    q("встроенные", "Что выведет код?", ["[3, 2, 1]", "[1, 2, 3]", "None", "ошибка"], 0,
      "reversed → итератор.", code="print(list(reversed([1, 2, 3])))"),
    q("списки", "Что выведет код?", ["None", "[1, 2, 3]", "[3, 2, 1]", "ошибка"], 0,
      "sort возвращает None.", code="print([3, 1, 2].sort())"),
    q("файлы", "Что делает with open?", ["закроет файл сам", "только откроет", "удалит файл", "залочит навсегда"], 0,
      "Контекстный менеджер.", code="with open('f.txt') as f:\n    data = f.read()"),
    q("исключения", "Что выведет код?", ["done", "err", "ошибка без печати", "nothing"], 0,
      "finally всегда.", code="try:\n    1/1\nfinally:\n    print('done')"),
    q("сравнения", "Что выведет код?", ["True", "False", "ошибка", "None"], 0,
      "Цепочка сравнений.", code="print(1 < 2 < 3)"),
    q("сравнения", "Что выведет код?", ["False", "True", "ошибка", "None"], 0,
      "2 < 3 ложно? 3 < 2 ложно → False.", code="print(3 < 2 < 1)"),
    q("байты", "Что выведет код?", ["[97, 98]", "['a', 'b']", "['ab']", "ошибка"], 0,
      "Итерация bytes → int.", code="print(list(b'ab'))"),
    q("f-string", "Что выведет код?", ["4", "2+2", "22", "ошибка"], 0,
      "Выражение в {}.", code="print(f'{2+2}')"),
    q("срезы", "Что выведет код?", ["[1, 9, 9, 2, 3]", "[1, 9, 9]", "[9, 9, 1, 2, 3]", "ошибка"], 0,
      "Вставка срезом.", code="a = [1, 2, 3]\na[1:1] = [9, 9]\nprint(a)"),
]

CODE_MIDDLE = [
    q("замыкания", "Что выведут все вызовы?", ["2 2 2", "0 1 2", "ошибка", "None None None"], 0,
      "Позднее связывание i.",
      code="funcs = []\nfor i in range(3):\n    funcs.append(lambda: i)\nprint(funcs[0](), funcs[1](), funcs[2]())"),
    q("замыкания", "Что выведут все вызовы?", ["0 1 2", "2 2 2", "ошибка", "1 1 1"], 0,
      "Default фиксирует i.",
      code="funcs = []\nfor i in range(3):\n    funcs.append(lambda i=i: i)\nprint(funcs[0](), funcs[1](), funcs[2]())"),
    q("генераторы", "Что выведет код?", ["0\n1\n2", "[0, 1, 2]", "ошибка", "None"], 0,
      "Генератор по next.",
      code="def g():\n    yield 0\n    yield 1\n    yield 2\nfor x in g():\n    print(x)"),
    q("генераторы", "Что будет после исчерпания?", ["StopIteration", "None", "IndexError", "False"], 0,
      "Протокол итератора.",
      code="g = (x for x in range(1))\nnext(g)\nnext(g)"),
    q("декораторы", "Что выведет код?", ["wrap\nf", "f\nwrap", "wrap", "f"], 0,
      "g = deco(g) при определении.",
      code="def deco(fn):\n    print('wrap')\n    return fn\n@deco\ndef f():\n    print('f')\nf()"),
    q("GIL", "Для CPU-bound в CPython лучше…", ["multiprocessing / native", "больше threading", "time.sleep", "print"], 0,
      "GIL мешает CPU threads.",
      code="# cpu_bound()\n# threading vs multiprocessing?"),
    q("asyncio", "Что нужно для await?", ["async def", "обычный def", "lambda", "class"], 0,
      "Только в корутине.",
      code="async def main():\n    await asyncio.sleep(0)"),
    q("dict", "В чём опасность?", ["один list на все ключи", "KeyError", "нет опасности", "deepcopy"], 0,
      "fromkeys шарит value.",
      code="d = dict.fromkeys(['a', 'b'], [])\nd['a'].append(1)\nprint(d['b'])"),
    q("comprehensions", "Утечёт ли i наружу?", ["нет (Py3)", "да как в 2.7", "ошибка", "только в dictcomp"], 0,
      "Свой scope у comprehension.",
      code="[i for i in range(3)]\n# i ?"),
    q("магические", "Что напечатает print(obj)?", ["hi", "Obj()", "ошибка", "None"], 0,
      "__str__ для print.",
      code="class Obj:\n    def __str__(self):\n        return 'hi'\nprint(Obj())"),
    q("itertools", "Что выведет list(islice(...))?", ["[0, 1, 2]", "[0,1,2,3,4]", "ошибка", "[]"], 0,
      "Первые 3.",
      code="from itertools import islice, count\nprint(list(islice(count(), 3)))"),
    q("functools", "Второй вызов heavy(2)?", ["из кэша, без print work", "снова work", "ошибка", "None"], 0,
      "lru_cache.",
      code="from functools import lru_cache\n@lru_cache\ndef heavy(x):\n    print('work')\n    return x*x\nheavy(2)\nheavy(2)"),
    q("context", "Что напечатает?", ["enter\nbody\nexit", "body\nenter\nexit", "enter\nexit\nbody", "ошибка"], 0,
      "Порядок CM.",
      code="class CM:\n    def __enter__(self):\n        print('enter')\n        return self\n    def __exit__(self, *a):\n        print('exit')\nwith CM():\n    print('body')"),
    q("typing", "Runtime проверка list[int]?", ["обычно нет", "да всегда TypeError", "только mypy runtime", "GIL check"], 0,
      "Аннотации не enforced.",
      code="def f(xs: list[int]):\n    return xs\nprint(f(['a']))"),
    q("dataclasses", "Что выведет код?", ["[1]", "[]", "ошибка shared", "None"], 0,
      "default_factory.",
      code="from dataclasses import dataclass, field\n@dataclass\nclass A:\n    xs: list = field(default_factory=list)\na, b = A(), A()\na.xs.append(1)\nprint(b.xs)"),
    q("sort", "Порядок при равном key?", ["стабильный (сохраняет порядок)", "random", "по id", "ошибка"], 0,
      "Timsort stable.",
      code="xs = [('b', 1), ('a', 1)]\nprint(sorted(xs, key=lambda t: t[1]))"),
    q("exceptions", "Что в e?", ["сообщение 'x'", "тип only", "traceback only", "None"], 0,
      "as e.",
      code="try:\n    raise ValueError('x')\nexcept ValueError as e:\n    print(e)"),
    q("args", "Как вызвать f?", ["f(a=1)", "f(1)", "оба", "никак"], 0,
      "keyword-only после *.",
      code="def f(*, a):\n    return a"),
    q("args", "Как вызвать f?", ["f(1)", "f(a=1)", "оба", "f()"], 0,
      "positional-only до /.",
      code="def f(a, /):\n    return a"),
    q("walrus", "Что выведет?", ["3 True", "True", "ошибка", "3"], 0,
      "Присвоение в выражении.",
      code="print((n := 3), n == 3)"),
    q("match", "Что выведет?", ["one", "other", "ошибка", "1"], 0,
      "case 1.",
      code="x = 1\nmatch x:\n    case 1:\n        print('one')\n    case _:\n        print('other')"),
    q("is", "Обычно для литерала 256?", ["True", "False", "ошибка", "None"], 0,
      "Кэш малых int.",
      code="print(256 is 256)"),
    q("performance", "Лучше для многих 'x in …'?", ["set", "list", "tuple всегда", "str"], 0,
      "Среднее O(1).",
      code="s = set(range(10000))\nprint(9999 in s)"),
    q("json", "Что будет с set?", ["TypeError без default", "станет list", "OK", "None"], 0,
      "set не JSON.",
      code="import json\njson.dumps({1, 2})"),
    q("pathlib", "Что получится?", ["Path('a/b') или a\\b", "ошибка", "ab", "list"], 0,
      "Оператор /.",
      code="from pathlib import Path\nprint(Path('a') / 'b')"),
]

CODE_SENIOR = [
    q("python", "Почему pop(0) медленный?", ["O(n) сдвиг", "O(1)", "GIL N", "hash"], 0,
      "Массив сдвигает элементы.",
      code="xs = list(range(10000))\nxs.pop(0)"),
    q("CPython", "dict сохраняет порядок вставки?", ["да, с 3.7 как контракт", "нет никогда", "только OrderedDict", "random"], 0,
      "Языковой guarantee.",
      code="print(list({'b': 1, 'a': 2}))"),
    q("GIL", "Два CPU-потока на чистом Python?", ["часто ≈ одно ядро", "линейный x2", "x4", "zero"], 0,
      "GIL.",
      code="# threading + pure python loop"),
    q("память", "__slots__ экономит за счёт?", ["нет __dict__ у экземпляра", "сжатия bytecode", "отключения GC", "mmap"], 0,
      "Фиксированные атрибуты.",
      code="class A:\n    __slots__ = ('x',)"),
    q("дескрипторы", "Instance attr затенит функцию?", ["да (non-data descriptor)", "нет", "ошибка", "только slots"], 0,
      "Функции — non-data.",
      code="class A:\n    def f(self): return 1\na = A()\na.f = 2\nprint(a.f)"),
    q("asyncio", "Почему нельзя time.sleep в async?", ["блокирует event loop", "убивает процесс", "TypeError always", "OK"], 0,
      "await asyncio.sleep.",
      code="async def bad():\n    import time\n    time.sleep(1)"),
    q("pickle", "pickle.loads(недовер.) риск?", ["RCE", "только большой RAM", "UTF error", "медленно"], 0,
      "Может исполнить код.",
      code="# pickle.loads(user_bytes)"),
    q("security", "shell=True риск?", ["injection", "только slow", "безопаснее list", "нет"], 0,
      "subprocess list args.",
      code="import subprocess\n# subprocess.run(user_str, shell=True)"),
    q("db", "N+1 выглядит как?", ["цикл запросов по связям", "один JOIN", "VACUUM", "index only"], 0,
      "ORM классика.",
      code="for u in users:\n    print(u.orders)  # lazy?"),
    q("cache", "Stampede это?", ["массовый промах кэша", "LRU overflow", "hash collision", "GIL thrash"], 0,
      "Singleflight/lock.",
      code="# cache miss storm"),
    q("python", "int('1'*100000) защита?", ["лимит str↔int digits", "нет защиты", "GIL", "float"], 0,
      "DoS mitigation.",
      code="import sys\n# sys.set_int_max_str_digits"),
    q("async", "CancelledError где ловить?", ["в await-точках / finally", "после return only", "в другом процессе", "никогда"], 0,
      "Кооперативная отмена.",
      code="async def work():\n    try:\n        await asyncio.sleep(10)\n    finally:\n        ..."),
    q("байткод", "Чем смотреть bytecode?", ["dis.dis", "ast only", "pdb only", "pip"], 0,
      "dis модуль.",
      code="import dis\ndef f(x): return x+1\ndis.dis(f)"),
    q("import", "circular import симптом?", ["частично инициализированный модуль / ImportError", "GIL dead", "SyntaxError", "OK always"], 0,
      "Локальный import / рефакторинг.",
      code="# a imports b, b imports a"),
    q("architecture", "Зачем ACL?", ["изолировать внешнюю модель", "ускорить SQL", "убрать тесты", "GIL"], 0,
      "Anti-corruption layer.",
      code="# external_dto -> domain_model"),
]


def all_code_extra():
    return CODE_JUNIOR, CODE_MIDDLE, CODE_SENIOR
