"""Ядро: карточки Middle."""
from __future__ import annotations

from bank.utils import q

MIDDLE: list[dict] = [
    q('декораторы', 'Декоратор @f над def g — это…', ['g = f(g)', 'f = g(f)', 'g вызывается сразу', 'синтаксический сахар import'], 0, 'Декоратор оборачивает функцию.'),
    q('декораторы', 'functools.wraps нужен чтобы…', ['сохранить __name__/__doc__ обёрнутой', 'ускорить вызов', 'добавить тип', 'заменить lambda'], 0, 'Копирует метаданные.'),
    q('декораторы', 'Декоратор с аргументами — это…', ['фабрика, возвращающая декоратор', 'невозможен', 'только class decorator', 'через eval'], 0, 'Тройная вложенность функций.'),
    q('генераторы', 'yield в функции делает её…', ['генератором', 'корутиной всегда', 'классом', 'итератором списка'], 0, 'generator function.'),
    q('генераторы', 'next(gen) после исчерпания…', ['StopIteration', 'None', 'IndexError', 'False'], 0, 'Протокол итератора.'),
    q('генераторы', 'Генератор хранит…', ['состояние между next', 'весь результат в RAM', 'только list', 'копию args'], 0, 'Ленивость и мало памяти.'),
    q('генераторы', '(x for x in range(3)) — это…', ['generator expression', 'tuple', 'list', 'set'], 0, 'Круглые скобки — genexp.'),
    q('итераторы', 'Итератор должен иметь…', ['__iter__ и __next__', 'только len', 'append', '__getitem__ обязательно'], 0, 'Протокол Iterator.'),
    q('итераторы', 'iter(x) вызывает…', ['x.__iter__()', 'x.__next__()', 'list(x)', 'x.next() в Py3'], 0, 'Получение итератора.'),
    q('context', 'Контекстный менеджер реализует…', ['__enter__/__exit__', 'open/close только', '__init__/__del__', 'with/as keywords внутри класса'], 0, 'Протокол with.'),
    q('context', 'contextlib.contextmanager превращает…', ['генератор в CM', 'класс в функцию', 'async в sync', 'list в with'], 0, 'yield разделяет enter/exit.'),
    q('comprehensions', 'Чем listcomp отличается от map+lambda часто?', ['читаемее для простых преобразований', 'всегда быстрее C', 'не создаёт list', 'запрещена в pep8'], 0, 'Стиль и ясность.'),
    q('closures', 'Замыкание — это…', ['функция с enclosing переменными', 'декоратор', 'класс', 'модуль'], 0, 'Captures nonlocal state.'),
    q('closures', 'nonlocal x нужен чтобы…', ['присваивать enclosing переменной', 'читать global', 'создать threadlocal', 'удалить x'], 0, 'Для записи в enclosing scope.'),
    q('GIL', 'GIL в CPython — это…', ['глобальная блокировка интерпретатора', 'сборщик мусора', 'тип данных', 'модуль threading'], 0, 'Один поток bytecode одновременно.'),
    q('GIL', 'GIL мешает…', ['CPU-bound многопоточности', 'I/O полностью', 'multiprocessing', 'asyncio I/O'], 0, 'Для CPU — multiprocessing/C-ext.'),
    q('threading', 'threading хорош для…', ['I/O-bound задач', 'чистого CPU всегда', 'замены asyncio', 'GPU'], 0, 'Пока ждёт I/O, GIL отпускается.'),
    q('multiprocessing', 'multiprocessing обходит GIL через…', ['отдельные процессы', 'больше потоков', 'снятие GIL флагом', 'JIT'], 0, 'Отдельные интерпретаторы.'),
    q('asyncio', 'async def объявляет…', ['корутину', 'поток', 'процесс', 'генератор синхронный'], 0, 'Coroutine function.'),
    q('asyncio', 'await можно внутри…', ['async def', 'любой функции', 'класса без async', 'lambda'], 0, 'Только в корутинах.'),
    q('asyncio', 'asyncio.gather запускает…', ['корутины конкурентно', 'строго по очереди всегда', 'потоки OS', 'процессы'], 0, 'Конкурентное ожидание.'),
    q('typing', 'list[int] в 3.9+ — это…', ['параметризованный тип', 'runtime list только int enforced', 'синтаксис ошибки до 3.12', 'tuple'], 0, 'Аннотация; runtime обычно не проверяет.'),
    q('typing', 'Optional[X] означает…', ['X | None', 'X обязателен', 'any', 'Union пустой'], 0, 'Синоним X | None.'),
    q('typing', 'Protocol нужен для…', ['структурной типизации (duck typing)', 'наследования классов', 'GIL', 'async'], 0, 'typing.Protocol / PEP 544.'),
    q('dataclasses', '@dataclass генерирует…', ['__init__, __repr__ и др.', 'только __slots__', 'SQL схему', 'JSON автоматом'], 0, 'Шаблон для data-holder.'),
    q('dataclasses', 'field(default_factory=list) зачем?', ['избежать shared mutable default', 'ускорить', 'сделать frozen', 'валидацию'], 0, 'Каждый экземпляр — свой list.'),
    q('slots', '__slots__ ограничивает…', ['набор атрибутов, экономит память', 'число методов', 'наследование', 'GC'], 0, 'Без __dict__ по умолчанию.'),
    q('MRO', 'MRO — это…', ['порядок поиска методов', 'модуль', 'тип ошибки', 'менеджер памяти'], 0, 'Method Resolution Order (C3).'),
    q('MRO', 'Class.__mro__ показывает…', ['цепочку базовых классов', 'только родителей 1 уровня', 'атрибуты', 'модули'], 0, 'Линеаризация наследования.'),
    q('property', '@property превращает метод в…', ['атрибут-геттер', 'статический метод', 'классметод', 'дескриптор записи только'], 0, 'Управляемый атрибут.'),
    q('classmethod', '@classmethod первый аргумент…', ['cls (класс)', 'self', 'args', 'нет аргументов'], 0, 'Метод класса.'),
    q('staticmethod', '@staticmethod…', ['не принимает self/cls автоматически', 'это глобальная функция модуля', 'запрещён', 'только в metaclasses'], 0, 'Обычная функция в пространстве класса.'),
    q('магические', '__str__ vs __repr__?', ['str для пользователя, repr для отладки', 'нет разницы', 'str только для print чисел', 'repr запрещён'], 0, 'PEP: repr ideally unambiguous.'),
    q('магические', '__eq__ определяет…', ['==', 'is', 'hash только', 'order <'], 0, 'Равенство значений.'),
    q('магические', 'Если __eq__ определён, __hash__…', ['часто ставят None для mutable', 'обязателен всегда', 'удаляется интерпретатором насильно', 'наследуется от object всегда ок'], 0, 'Mutable с eq не должны быть hashable.'),
    q('копирование', 'copy.copy — это…', ['shallow copy', 'deep copy', 'ссылка', 'pickle'], 0, 'Поверхностная копия.'),
    q('копирование', 'copy.deepcopy нужен когда…', ['есть вложенные изменяемые', 'всегда вместо =', 'для int', 'для None'], 0, 'Рекурсивное копирование.'),
    q('pickle', 'pickle используется для…', ['сериализации объектов Python', 'JSON веба', 'SQL', 'XML'], 0, 'Бинарная сериализация; осторожно с security.'),
    q('json', 'json не сериализует напрямую…', ['set, сложные объекты', 'dict', 'list', 'str'], 0, 'Нужен default hook / конвертация.'),
    q('регулярки', 'Модуль regex?', ['re', 'regex встроен всегда', 'grep', 'pattern'], 0, 'Стандартный re.'),
    q('регулярки', 're.compile полезен когда…', ['паттерн переиспользуется', 'один раз', 'вместо str.find нельзя', 'для bytes только'], 0, 'Компиляция один раз.'),
    q('collections', 'defaultdict(int) при отсутствии ключа…', ['создаёт 0', 'KeyError', 'None', 'False'], 0, 'default_factory вызывается.'),
    q('collections', "Counter('aab')['a']?", ['2', '1', '0', 'ошибка'], 0, 'Подсчёт элементов.'),
    q('collections', 'namedtuple — это…', ['легковесный immutable с именами полей', 'dict', 'dataclass', 'list'], 0, 'tuple + атрибуты.'),
    q('collections', 'deque хорош для…', ['быстрых append/pop с обоих концов', 'случайного доступа O(1) лучше list', 'ключей dict', 'матриц'], 0, 'Двусторонняя очередь.'),
    q('itertools', 'itertools.chain склеивает…', ['итерируемые лениво', 'только list', 'dict', 'строки обязательно'], 0, 'Последовательная итерация.'),
    q('itertools', 'islice(it, 10) — это…', ['первые 10 элементов лениво', 'сортировка', 'shuffle', 'deep copy'], 0, 'Срез итератора.'),
    q('functools', 'lru_cache — это…', ['мемоизация с лимитом', 'LRU список', 'async lock', 'GC hint'], 0, 'Кэш результатов функции.'),
    q('functools', 'partial(f, 1) делает…', ['новую функцию с зафиксированным аргументом', 'вызов f', 'копию кода f', 'декоратор класса'], 0, 'Частичное применение.'),
    q('исключения', 'raise X from Y связывает…', ['__cause__', 'только message', 'traceback удаляет', 'suppress'], 0, 'Exception chaining.'),
    q('исключения', 'contextlib.suppress(Error)…', ['игнорирует указанные исключения', 'логирует', 'превращает в warning', 'fatal'], 0, 'Молчаливый пропуск.'),
    q('EAFP', 'EAFP означает…', ['Easier to Ask Forgiveness than Permission', 'Always Find Path', 'Error After Function', 'Python anti-pattern'], 0, 'try/except вместо долгих проверок.'),
    q('LBYL', 'LBYL — это…', ['Look Before You Leap', 'Lazy Binding', 'List By Yield', 'Linux Build'], 0, 'Проверки до действия.'),
    q('args', 'def f(*, a): — a это…', ['keyword-only', 'positional-only', 'optional', 'variadic'], 0, '* отделяет keyword-only.'),
    q('args', 'def f(a, /): — a это…', ['positional-only', 'keyword-only', 'kwargs', 'default'], 0, '/ — positional-only (PEP 570).'),
    q('import', 'circular import — проблема когда…', ['модули импортируют друг друга на top-level', 'есть venv', 'много функций', 'typing'], 0, 'Лечится локальным import / рефакторингом.'),
    q('пакеты', '__init__.py historically…', ['делает каталог пакетом', 'обязателен всегда в 3.3+', 'запускает pip', 'кэш'], 0, 'Namespace packages могут без него.'),
    q('тесты', 'pytest находит тесты по…', ['имени test_* / *_test', 'любому .py', 'main', 'doctest only'], 0, 'Конвенции discovery.'),
    q('тесты', 'fixture в pytest — это…', ['подготовка данных/ресурсов', 'assert', 'мок только', 'CI job'], 0, '@pytest.fixture.'),
    q('mock', 'unittest.mock.patch подменяет…', ['объект в пространстве имён', 'исходник на диске', 'GIL', 'байткод навсегда'], 0, 'Временная подмена.'),
    q('логирование', 'Предпочтительнее print для libs…', ['logging', 'sys.stdout.write только', 'input', 'warnings всегда'], 0, 'Модуль logging.'),
    q('pathlib', "Path('a') / 'b' даёт…", ["Path('a/b')", 'ошибку', "str 'a/b'", 'list'], 0, 'Оператор / для Path.'),
    q('enum', 'enum.Enum нужен для…', ['именованных констант', 'float', 'async', 'GIL flags'], 0, 'Перечисления.'),
    q('match', 'match/case появился в…', ['3.10', '3.8', '2.7', '3.12'], 0, 'Structural pattern matching.'),
    q('walrus', 'Для чего в условии пишут (n := len(a)) > 0?', ['присваивание в выражении', 'аннотацию', 'decorator', 'comprehension only'], 0, 'PEP 572: моржовый оператор присваивает и сразу использует значение.'),
    q('f-string', "f'{x=!r}' покажет…", ['имя и repr значения', 'только x', 'ошибку до 3.12', 'hex'], 0, 'Debug self-documenting.'),
    q('bytes', 'encode/decode связывает…', ['str ↔ bytes', 'list ↔ tuple', 'int ↔ float', 'json ↔ dict'], 0, 'Текстовые кодировки.'),
    q('ООП', 'super() используется для…', ['вызова метода родителя по MRO', 'создания потока', 'импорта', 'GC'], 0, 'Кооперативное наследование.'),
    q('ООП', 'Миксин обычно…', ['класс с доп. поведением без самостоятельной роли', 'абстрактный модуль', 'декоратор', 'metaclasses only'], 0, 'Multiple inheritance utility.'),
    q('ABC', 'abc.ABC / @abstractmethod…', ['запрещает инстанс без реализации', 'ускоряет', 'добавляет slots', 'заменяет Protocol'], 0, 'Номинальные абстрактные классы.'),
    q('дескрипторы', 'Дескриптор — объект с…', ['__get__/__set__/__delete__', 'только __call__', 'yield', 'async'], 0, 'Протокол дескрипторов; property на нём.'),
    q('weakref', 'weakref нужен чтобы…', ['ссылаться без удержания GC', 'ускорить dict', 'шифровать', 'сериализовать'], 0, 'Слабые ссылки.'),
    q('GC', 'Сборщик циклических ссылок — это…', ['gc модуль / cyclic GC', 'только refcount', 'GIL', 'swap'], 0, 'refcount + periodic cycle detection.'),
    q('refcount', 'sys.getrefcount(obj)…', ['считает ссылки (+временные)', 'размер байт', 'hash', 'id'], 0, 'Включая временные при вызове.'),
    q('performance', 'Для многих membership checks лучше…', ['set', 'list', 'tuple всегда', 'queue'], 0, 'Среднее O(1) у set.'),
    q('performance', 'Конкатенация много str в цикле…', ['лучше join', '+= всегда ок', 'f-string в цикле идеал', 'bytearray обязателен'], 0, "''.join(parts) эффективнее."),
    q('sort', 'sorted(xs, key=lambda x: x[1])…', ['сортирует по второму элементу', 'удаляет', 'группирует', 'хеширует'], 0, 'key function.'),
    q('sort', 'Сортировка в Python…', ['стабильная (Timsort)', 'unstable', 'quicksort гарантирован', 'только числа'], 0, 'Стабильный Timsort.'),
    q('исключения', 'except Exception as e: — e доступен…', ['в блоке except (и очищается после в 3)', 'глобально', 'в finally всегда', 'никогда'], 0, 'Имя исключения.'),
    q('with', 'Несколько контекстов: with A() as a, B() as b', ['да, поддерживается', 'нет', 'только async with', 'только 3.12+'], 0, 'Несколько CM в одном with.'),
    q('generators', 'yield from subgen…', ['делегирует итерацию подгенератору', 'копирует list', 'создаёт thread', 'закрывает файл'], 0, 'PEP 380.'),
    q('coroutines', 'gen.send(x) передаёт…', ['значение в yield', 'в return', 'в global', 'в GIL'], 0, 'Двусторонние генераторы.'),
    q('typing', 'TypedDict описывает…', ['словари с известными ключами/типами', 'list', 'dataclass', 'Enum'], 0, 'Типизация dict-структур.'),
    q('typing', "Literal['a','b'] означает…", ['только эти значения', 'любой str', 'Enum автоматом', 'bytes'], 0, 'Буквальные типы.'),
    q('dataclasses', 'frozen=True делает…', ['приблизительно immutable экземпляр', 'slots', 'slots+dict', 'JSON'], 0, 'Запрет присваивания полей.'),
    q('attrs/pydantic', 'Pydantic в отличие от dataclass часто…', ['валидирует данные на runtime', 'только генерирует __init__', 'заменяет GIL', 'компилирует C'], 0, 'Валидация и парсинг.'),
    q('HTTP', 'Популярная sync HTTP библиотека?', ['requests', 'http.client только принято', 'urllib обязателен везде', 'socket сырой'], 0, 'requests — de facto.'),
    q('HTTP', 'httpx хорош тем что…', ['поддерживает sync и async', 'только Python 2', 'заменяет Django', 'встроен в stdlib'], 0, 'Современный клиент.'),
    q('WSGI', 'WSGI — это…', ['интерфейс sync веб-приложений', 'async сервер', 'ORM', 'шаблонизатор'], 0, 'PEP 3333.'),
    q('ASGI', 'ASGI — это…', ['async интерфейс Python веб-приложений', 'старый CGI', 'замена TCP', 'тип list'], 0, 'Django/FastAPI/Starlette.'),
    q('FastAPI', 'FastAPI строится вокруг…', ['type hints + ASGI', 'только Flask sync', 'GIL removal', 'GUI'], 0, 'Аннотации → OpenAPI/валидация.'),
    q('SQL', 'SQLAlchemy — это…', ['ORM/toolkit для БД', 'NoSQL база', 'кэш Redis', 'брокер'], 0, 'Популярный ORM.'),
    q('DI', 'Dependency Injection помогает…', ['тестируемости и слабой связанности', 'ускорить GIL', 'уменьшить RAM магией', 'заменить типы'], 0, 'Явные зависимости.'),
    q('замыкания', 'Что напечатают funcs[0]() при классической ошибке позднего связывания?', ['2', '0', '1', 'ошибка'], 0, 'Без значения по умолчанию все замыкания видят финальный i.', code='funcs = []\nfor i in range(3):\n    funcs.append(lambda: i)\n# funcs[0]()'),
    q('замыкания', 'Как зафиксировать i в lambda в цикле?', ['lambda i=i: i', 'lambda: i.copy()', 'global i', 'nonlocal i в цикле'], 0, 'Default arg связывается в момент определения.'),
    q('listcomp', 'Что вернёт [i for i in range(5) if i%2==0]?', ['[0, 2, 4]', '[1, 3]', '[0,1,2,3,4]', 'ошибка'], 0, 'Фильтр в comprehension.'),
    q('dict', "dict.fromkeys(['a','b'], []) — опасность?", ['один и тот же list на все ключи', 'KeyError', 'нет опасности', 'глубокая копия'], 0, 'value не копируется.'),
    q('is', 'Малые int кэшируются; обычно (256 is 256)…', ['True', 'False', 'ошибка', 'зависит от OS только'], 0, 'Interning малых целых в CPython.'),
    q('is', 'Обычно (257 is 257) для литералов в одном выражении…', ['часто True из-за peephole, но не контракт', 'всегда False', 'ошибка', 'None'], 0, 'На identity int полагаться нельзя — используйте ==.'),
    q('строки', 'Интернирование строк: sys.intern', ['принудительно дедуплицирует str', 'шифрует', 'делает bytes', 'GC disable'], 0, 'Для частых ключей.'),
    q('memoryview', 'memoryview нужен для…', ['работы со срезами bytes без копирования', 'GUI', 'JSON', 'async sleep'], 0, 'Буферный протокол.'),
    q('struct', 'struct.pack упаковывает…', ['значения в bytes по формату', 'JSON', 'pickle', 'XML'], 0, 'Бинарные форматы.'),
    q('array', 'array.array vs list?', ['типизированный компактный массив', 'то же самое', 'всегда быстрее dict', 'immutable'], 0, 'Однотипные числовые значения.'),
    q('декораторы', 'Порядок @a @b def f: это…', ['f = a(b(f))', 'f = b(a(f))', 'параллельно', 'ошибка'], 0, 'Ближний декоратор применяется первым.'),
    q('генераторы', 'list(x for x in range(3))?', ['[0,1,2]', 'generator object print', 'tuple', 'ошибка'], 0, 'list поглощает genexp.'),
    q('генераторы', 'return value в генераторе (3.3+)…', ['кладёт value в StopIteration.value', 'синтаксическая ошибка', 'как обычный return из caller', 'игнорируется'], 0, 'PEP 380: return x в generator → StopIteration.value = x.'),
    q('async', 'async for нужен для…', ['async-итераторов', 'обычных list', 'threading', 'multiprocessing'], 0, '__aiter__/__anext__.'),
    q('async', 'async with нужен для…', ['async context managers', 'обычного open только', 'threads', 'files sync'], 0, '__aenter__/__aexit__.'),
    q('typing', 'Union[int, str] эквивалент 3.10+…', ['int | str', 'int & str', 'Optional', 'Any'], 0, 'PEP 604.'),
    q('typing', 'Final[x] означает…', ['не должен переназначаться', 'константа CPU', 'frozen dataclass', 'slots'], 0, 'Для чекеров.'),
    q('typing', 'Annotated[int, ...] несёт…', ['метаданные для инструментов', 'runtime check обязательно', 'GIL hint', 'скорость'], 0, 'PEP 593.'),
    q('dataclasses', 'asdict(obj) делает…', ['рекурсивно в dict', 'json string', 'pickle', 'slots'], 0, 'dataclasses.asdict.'),
    q('collections', 'ChainMap полезен для…', ['слоя переопределений mapping', 'SQL join', 'async gather', 'heap'], 0, 'Просмотр нескольких dict.'),
    q('heapq', 'heapq реализует…', ['бинарную кучу на list', 'AVL', 'B-tree', 'deque'], 0, 'Приоритетная очередь.'),
    q('bisect', 'bisect модуль для…', ['бинарного поиска/вставки в sorted list', 'быстрой сортировки', 'hash', 'GIL'], 0, 'Поддержание порядка.'),
    q('tempfile', 'NamedTemporaryFile удаляется…', ['часто при закрытии (зависит от delete)', 'никогда', 'только reboot', 'вручную обязателен всегда'], 0, 'Параметр delete.'),
    q('pathlib', 'Path.read_text()…', ['читает файл как str', 'bytes only', 'json', 'lines iterator always'], 0, 'Удобный helper.'),
    q('subprocess', 'capture_output=True в run…', ['собирает stdout/stderr', 'shell=True', 'async', 'ignore'], 0, 'subprocess.run.'),
    q('dataclasses', 'kw_only=True (3.10)…', ['поля только keyword', 'frozen', 'slots', 'order'], 0, 'Keyword-only fields.'),
    q('match', 'case _ : означает…', ['wildcard / default', 'ошибку', 'None only', 'ellipsis object'], 0, 'Шаблон по умолчанию.'),
    q('match', 'case [x, *rest]:', ['матчит последовательность', 'только list тип строго runtime class', 'dict', 'set'], 0, 'Sequence pattern.'),
    q('exceptions', 'Exception.__notes__ (3.11)…', ['доп. заметки к исключению', 'stack only', 'warnings', 'logs'], 0, 'add_note.'),
    q('warnings', 'warnings.filterwarnings управляет…', ['показом предупреждений', 'exceptions', 'logs level only', 'GIL'], 0, 'Модуль warnings.'),
    q('import', 'importlib.reload…', ['перезагружает модуль', 'удаляет пакет', 'чистит pip', 'restart OS'], 0, 'Осторожно с состоянием.'),
    q('ABC', '@abstractmethod на property…', ['возможно', 'нельзя', 'только methods', 'только classmethod'], 0, 'Абстрактные property.'),
    q('protocols', 'runtime_checkable Protocol…', ['isinstance может проверить методы', 'всегда без runtime', 'заменяет ABC полностью без оговорок', 'GIL'], 0, 'Ограниченная runtime проверка.'),
    q('functools', 'singledispatch — это…', ['мультиметод по типу 1-го аргумента', 'async gather', 'cache', 'partial only'], 0, 'functools.singledispatch.'),
    q('functools', 'cached_property…', ['кэш на экземпляре', 'lru глобальный', 'classmethod', 'slots'], 0, 'Пересчёт один раз.'),
    q('itertools', 'groupby требует…', ['часто предварительной сортировки по ключу', 'dict', 'set', 'async'], 0, 'Группирует подряд идущие.'),
    q('itertools', "list(product('ab', repeat=2))?", ["[('a', 'a'), ('a', 'b'), ('b', 'a'), ('b', 'b')]", "['ab']", "['a', 'b']", 'ошибка'], 0, 'Декартово произведение.'),
    q('itertools', 'cycle([1,2])…', ['бесконечно повторяет', 'один проход', 'shuffle', 'sort'], 0, 'Бесконечный итератор.'),
    q('операторы', 'Допустим ли синтаксис a := b := 1?', ['запрещён (SyntaxError)', 'допустим как a = b = 1', 'только в if', 'только 3.12'], 0, 'Цепочка walrus так нельзя. Нужно a = b = 1 или (a := (b := 1)).'),
    q('comprehensions', 'Есть ли у listcomp своей scope?', ['да (с 3), локальные переменные не утекают', 'нет как в 2.7', 'только для async', 'только dictcomp'], 0, 'Leak фиксанули.'),
    q('GIL', 'numpy отпускает GIL в тяжёлых C-циклах часто…', ['да, многие операции', 'никогда', 'только print', 'только на Windows'], 0, 'C-extensions pattern.'),
    q('memory', 'sys.getsizeof([1,2]) учитывает…', ['overhead контейнера, не глубоко элементы всегда', 'всю глубокую структуру', 'только int', 'disk'], 0, 'Не deep size.'),
    q('json', 'json.loads vs load?', ['строка vs file object', 'нет разницы', 'bytes vs path', 'pickle'], 0, 's = string.'),
    q('csv', 'csv.DictReader читает…', ['строки как dict по заголовку', 'JSON', 'pickle', 'YAML'], 0, 'Модуль csv.'),
    q('sqlite', 'sqlite3 в stdlib…', ['встроенная БД в файле/памяти', 'клиент Postgres', 'Redis', 'Mongo'], 0, 'Удобно для локального.'),
    q('hashlib', 'hashlib.sha256 нужен для…', ['криптографического хеша', 'hash() dict', 'id()', 'random'], 0, 'Не путать с hash().'),
    q('secrets', 'secrets модуль лучше random для…', ['токенов/криптографии', 'shuffle колоды в игре ok всегда', 'math sim', 'sort'], 0, 'Криптостойкость.'),
    q('dataclasses', 'slots=True (3.10+) у dataclass…', ['генерирует __slots__', 'frozen', 'kw_only', 'JSON'], 0, 'Экономия памяти.'),
    q('typing', 'TypedDict total=False…', ['ключи опциональны', 'запрещены', 'только str values', 'frozen'], 0, 'Частичные словари.'),
    q('HTTP', 'idempotent методы HTTP обычно…', ['GET PUT DELETE', 'POST только', 'PATCH always', 'CONNECT'], 0, 'Семантика HTTP.'),
    q('декораторы', '@decorator без скобок vs @decorator()…', ['объект vs вызов фабрики', 'нет разницы', 'скобки запрещены', 'только для class'], 0, '() нужны, если декоратор-фабрика.'),
    q('замыкания', 'cell в замыкании хранит…', ['cell_contents enclosing переменной', 'bytecode', 'GIL lock', 'только int'], 0, '__closure__.'),
    q('генераторы', 'gen.close() вызывает в генераторе…', ['GeneratorExit', 'StopIteration только', 'KeyboardInterrupt', 'ничего'], 0, 'Завершение генератора.'),
    q('генераторы', 'Генератор — одноразовый?', ['да, после исчерпания пуст', 'нет, рестарт сам', 'как list', 'кэшируется'], 0, 'Нужен новый вызов функции.'),
    q('итераторы', 'У list итератор отдельный объект?', ['да', 'нет, list is iterator', 'только для tuple', 'только dict'], 0, 'iter(list) создаёт list_iterator.'),
    q('context', 'Если __exit__ вернул True…', ['подавляет исключение', 'ре-рейзит всегда', 'закрывает GIL', 'игнор return'], 0, 'Swallow exception.'),
    q('GIL', 'Время переключения GIL roughly связано с…', ['check interval / eval breaker', 'только OS quantum', 'GC only', 'pip'], 0, 'sys.setswitchinterval.'),
    q('threading', 'Lock.acquire в том же потоке повторно без RLock…', ['дедлок', 'ok', 'ошибка импорта', 'auto-release'], 0, 'Обычный Lock не реентерабелен.'),
    q('threading', 'RLock отличается тем что…', ['реентерабельный', 'быстрее всегда', 'для процессов', 'async only'], 0, 'Можно acquire несколько раз одним потоком.'),
    q('multiprocessing', 'Queue между процессами…', ['сериализует объекты', 'делит память напрямую always', 'только str', 'GIL share'], 0, 'Через pickle/IPC.'),
    q('asyncio', 'create_task планирует…', ['выполнение корутины на loop', 'OS thread', 'process', 'sync call'], 0, 'Task на event loop.'),
    q('asyncio', 'run_in_executor нужен для…', ['блокирующего кода в thread/process pool', 'быстрее await sleep', 'замены gather', 'GUI only'], 0, 'Не блокировать loop.'),
    q('typing', 'NoReturn означает…', ['функция не возвращает нормально', 'return None', 'Any', 'Never only 2.7'], 0, 'Всегда бросает/exit.'),
    q('typing', 'TypedDict vs dataclass?', ['TypedDict для dict-форм, dataclass — объекты', 'одно и то же', 'TypedDict runtime class always', 'dataclass только JSON'], 0, 'Разные модели данных.'),
    q('typing', 'Unpack/TypeVarTuple связаны с…', ['вариативными generics', 'GIL', 'async', 'pathlib'], 0, 'PEP 646.'),
    q('dataclasses', 'order=True добавляет…', ['сравнения < <= и т.д.', 'hash всегда', 'slots', 'JSON'], 0, 'По полям по порядку.'),
    q('dataclasses', 'InitVar — это…', ['поле только для __init__, не хранится', 'classmethod', 'property', 'slots field'], 0, 'Init-only.'),
    q('collections', 'UserDict зачем?', ['удобное наследование под dict-like', 'быстрее dict', 'замена OrderedDict', 'async map'], 0, 'Обёртка для кастомизации.'),
    q('collections', 'OrderedDict всё ещё нужен после 3.7?', ['для move_to_end / equality по порядку и явного API', 'нет никогда', 'только PyPy', 'для set'], 0, 'Специфичные методы.'),
    q('itertools', 'tee(it, n)…', ['разветвляет итератор (с буфером)', 'копирует list', 'shuffle', 'sort'], 0, 'Память растёт, если ветки расходятся.'),
    q('itertools', 'list(accumulate([1,2,3]))?', ['[1, 3, 6]', '[6]', '[1, 2, 3]', 'ошибка'], 0, 'Накопительная сумма.'),
    q('functools', 'reduce(lambda a,b:a+b, [1,2,3])?', ['6', '[1,2,3]', 'ошибка', 'None'], 0, 'Свёртка.'),
    q('functools', 'total_ordering помогает…', ['достроить сравнения из немногих методов', 'сортировать быстрее C', 'GIL', 'hash'], 0, 'Класс-декоратор.'),
    q('исключения', 'except* (3.11) ловит…', ['подисключения ExceptionGroup', 'только async', 'BaseExceptionGroup нельзя', 'синтаксис 3.8'], 0, 'PEP 654.'),
    q('тесты', 'monkeypatch в pytest…', ['временно патчит атрибуты/env', 'меняет CPython', 'удаляет тесты', 'CI matrix'], 0, 'Изоляция сайд-эффектов.'),
    q('тесты', 'parametrize нужен для…', ['набора вход→ожидание', 'фикстур только', 'моков', 'coverage'], 0, '@pytest.mark.parametrize.'),
    q('pathlib', 'Path.resolve()…', ['абсолютный путь + symlink resolve', 'только str', 'удаляет файл', 'chmod'], 0, 'Канонический путь.'),
    q('регулярки', 're.VERBOSE позволяет…', ['комментарии и пробелы в паттерне', 'быстрее match', 'только bytes', 'JIT'], 0, 'Читаемые regex.'),
    q('json', 'default= в dumps…', ['сериализатор неизвестных типов', 'indent', 'encoding', 'sort_keys'], 0, 'Хук для set/datetime и т.п.'),
    q('performance', 'Генератор vs list для большого потока…', ['генератор экономит память', 'list всегда быстрее и лучше', 'без разницы', 'GIL снимает'], 0, 'Ленивость.'),
    q('sort', 'key= должен быть…', ['вызываемым, вызывается раз на элемент (декоратор)', 'cmp как в Py2 обязателен', 'async', 'hash'], 0, 'Schwartzian transform внутри.'),
    q('магические', '__len__ должен возвращать…', ['int >= 0', 'любой float', 'str', 'None'], 0, 'Иначе TypeError/ValueError.'),
    q('магические', '__bool__ если нет, берётся…', ['__len__ != 0', 'всегда True', 'hash', 'id'], 0, 'Правдивость объектов.'),
    q('property', 'obj.x = 1 при property без setter…', ['AttributeError', 'создаст в __dict__ всегда', 'ok', 'TypeError only'], 0, 'Read-only property.'),
    q('MRO', 'diamond inheritance решает…', ['C3 linearization', 'случайный порядок', 'только первый parent', 'запрет syntax'], 0, 'Предсказуемый MRO.'),
    q('ABC', 'Можно ли инстанцировать ABC без abstract методов?', ['да', 'нет никогда', 'только Protocol', 'только mixin'], 0, 'Абстрактность из-за abstract methods.'),
    q('weakref', 'WeakValueDictionary хранит…', ['слабые ссылки на значения', 'сильные на ключи и значения', 'только int', 'файлы'], 0, 'GC может удалить value.'),
    q('copy', 'Для объекта с циклическими ссылками deepcopy…', ['справляется через memo', 'всегда падает', 'игнорирует циклы молча теряя', 'запрещён'], 0, 'memo dict.'),
    q('HTTP', 'requests.get timeout…', ['ограничивает ожидание', 'обязателен всегда синтаксисом', 'только connect', 'async only'], 0, 'Защита от зависаний.'),
    q('ASGI', 'Starlette/FastAPI — это…', ['ASGI-фреймворки', 'только WSGI', 'GUI', 'ORM'], 0, 'Асинхронный стек.'),
    q('SQL', 'session.rollback в SQLAlchemy…', ['отменяет транзакцию', 'drop table', 'vacuum', 'commit'], 0, 'Откат.'),
    q('match', "case {'x': v} матчит…", ['mapping с ключом x', 'только dict subclass строго без Protocol', 'list', 'set'], 0, 'Mapping pattern.'),
    q('args', 'def f(*args, **kwargs) порядок в сигнатуре…', ['*args затем **kwargs', '**kwargs затем *args', 'любой', 'только kwargs'], 0, 'Синтаксическое правило.'),
    q('import', 'from __future__ import annotations делает…', ['откладывает оценку аннотаций (строки)', 'включает GIL free', 'Py2 mode', 'оптимизирует abs'], 0, 'PEP 563/649 эпоха.'),
    q('enum', 'auto() в Enum…', ['автозначения', 'random', 'hash', 'None'], 0, 'enum.auto.'),
    q('logging', 'logger.exception внутри except…', ['лог + traceback', 'только message', 'raise снова', 'silence'], 0, 'Удобный helper.'),
    q('subprocess', 'check=True в run…', ['бросит CalledProcessError при ненулевом коде', 'игнор код', 'shell', 'timeout'], 0, 'Строгая проверка статуса.'),
]
