"""Ядро: карточки Senior."""
from __future__ import annotations

from bank.utils import q

SENIOR: list[dict] = [
    q('CPython', 'Основная структура объекта CPython?', ['PyObject (refcount + type)', 'только указатель', 'JVM object header', 'Go interface'], 0, 'Все объекты — PyObject-совместимы.'),
    q('CPython', 'Словари CPython оптимизированы как…', ['compact + insertion-ordered (3.6+)', 'hash table без порядка', 'tree map', 'B-tree'], 0, 'Порядок вставки — язык. контракт с 3.7.'),
    q('GIL', 'Как C-расширение отпускает GIL?', ['Py_BEGIN_ALLOW_THREADS', 'gil.disable()', 'threading.ungil', 'нельзя'], 0, 'Макросы ALLOW/END_ALLOW_THREADS.'),
    q('GIL', 'free-threading (PEP 703) цель…', ['опционально убрать GIL', 'ускорить single-thread 10x всегда', 'заменить asyncio', 'удалить refcount'], 0, 'Эксперименты в 3.13+.'),
    q('память', 'pymalloc — это…', ['аллокатор мелких объектов CPython', 'OS malloc только', 'GPU heap', 'swap file'], 0, 'Арена/пулы для small allocs.'),
    q('память', '__slots__ экономит за счёт…', ['отказа от per-instance __dict__', 'сжатия bytecode', 'отключения GC', 'mmap'], 0, 'Фиксированные дескрипторы.'),
    q('GC', 'gc.freeze() используется…', ['чтобы не трейсить старые объекты после fork/copy-on-write', 'удалить GIL', 'очистить RAM сразу', 'disable refcount'], 0, 'Оптимизация для copy-on-write.'),
    q('import', 'importlib позволяет…', ['программный импорт и лоадеры', 'только pip', 'компиляцию C', 'удаление sys'], 0, 'Метапуть импорта.'),
    q('import', 'sys.meta_path — это…', ['finders для импорта', 'PYTHONPATH str', 'site-packages list only', 'GIL queue'], 0, 'PEP 302/451.'),
    q('байткод', 'dis.dis показывает…', ['байткод функции', 'машинный asm x86 всегда', 'IR LLVM', 'AST только'], 0, 'Дизассемблер bytecode.'),
    q('байткод', '.compile / ast.parse связаны с…', ['компиляцией в code object', 'сетевым RPC', 'SQL', 'GIL'], 0, 'Фронтенд интерпретатора.'),
    q('дескрипторы', 'Data descriptor имеет…', ['__set__/__delete__ (+ __get__)', 'только __get__', 'только __call__', 'slots'], 0, 'Перебивает instance dict.'),
    q('дескрипторы', 'Non-data descriptor…', ['только __get__, слабее instance __dict__', 'сильнее всегда', 'запрещён', 'это property.setter'], 0, 'Функции — non-data descriptors.'),
    q('метаклассы', 'Метакласс — это…', ['класс класса (type subclass)', 'декоратор', 'модуль', 'ABC'], 0, 'type(name, bases, ns).'),
    q('метаклассы', 'class A(metaclass=M): вызывает…', ['M(name, bases, namespace)', 'A.__new__ только', 'import hook', 'GC'], 0, 'Создание класса.'),
    q('метаклассы', '__init_subclass__ полезен чтобы…', ['хукать создание подклассов без метакласса', 'заменить __init__', 'GIL', 'slots auto'], 0, 'PEP 487.'),
    q('typing', 'typing.overload нужен для…', ['нескольких сигнатур для чекера', 'runtime dispatch обязательно', 'ускорения', 'decorators'], 0, 'Только для type checkers.'),
    q('typing', 'TypeVar bound=… ограничивает…', ['верхнюю границу параметра типа', 'runtime cast', 'GIL', 'slots'], 0, 'Generics.'),
    q('typing', 'ParamSpec / Concatenate для…', ['типизации декораторов (*args/**kwargs)', 'list[int]', 'Enum', 'async IO'], 0, 'PEP 612.'),
    q('typing', 'LiteralString (3.11) помогает…', ['отличать доверенные строки от произвольных', 'шифровать', 'intern', 'bytes'], 0, 'Анти-SQL-injection в типах.'),
    q('concurrency', 'concurrent.futures даёт…', ['Thread/ProcessPoolExecutor', 'только asyncio', 'GIL kill', 'GPU'], 0, 'Высокоуровневые пулы.'),
    q('concurrency', 'Когда ProcessPool лучше ThreadPool?', ['CPU-bound в CPython', 'чистый network wait', 'всегда', 'никогда'], 0, 'Обход GIL ценой IPC.'),
    q('asyncio', 'Semaphore vs Lock в asyncio?', ['Semaphore допускает N, Lock — 1', 'нет разницы', 'Lock для процессов', 'Semaphore sync only'], 0, 'Ограничение конкурентности.'),
    q('asyncio', 'asyncio.TaskGroup (3.11)…', ['структурированное конкурентное выполнение задач', 'замена threading', 'удаляет loop', 'GIL'], 0, 'Structured concurrency.'),
    q('asyncio', 'Почему блокирующий вызов в async плох?', ['блокирует event loop', 'убивает процесс', 'ломает типы', 'обязателен'], 0, 'Используйте to_thread / executors.'),
    q('asyncio', 'loop.add_signal_handler доступен…', ['не на всех платформах (ограничения Windows)', 'везде одинаково', 'только в threads', 'в PyPy only'], 0, 'Платформенные нюансы.'),
    q('multiprocessing', 'spawn vs fork start method…', ['разный способ старта процесса и совместимость', 'только имена', 'GIL modes', 'async'], 0, 'macOS/Windows default spawn.'),
    q('pickle', 'Почему pickle опасен из недоверенного источника?', ['может выполнить код при загрузке', 'только большой размер', 'ломает UTF-8', 'медленный hash'], 0, 'Arbitrary code execution.'),
    q('security', 'Для секретов в логах важно…', ['редактирование / не логировать', 'print всегда', 'pickle secrets', 'держать в URL'], 0, 'Leak prevention.'),
    q('API design', 'Хороший API в Python часто…', ['явный, предсказуемый, с типами', 'максимум магии __getattr__', 'глобальные синглтоны везде', 'молчаливые catch-all except'], 0, 'Явное лучше неявного (Zen).'),
    q('Zen', '«Explicit is better than implicit» из…', ['The Zen of Python (PEP 20)', 'PEP 8 только', 'GIL docs', 'POSIX'], 0, 'import this.'),
    q('SOLID', 'Как в Python обычно реализуют Dependency Inversion?', ['протоколы/ABC + DI', 'глобальные import', 'GIL', 'monkeypatch в проде'], 0, 'Модули верхнего уровня зависят от абстракций, а не от конкретных классов.'),
    q('patterns', 'В Python Singleton часто заменяют…', ['модулем как синглтоном', 'обязательным metaclass везде', 'Borg только', 'GoF строго'], 0, 'Модуль загружается один раз.'),
    q('patterns', 'Стратегия естественно выражается…', ['функциями/callable первого класса', 'только наследованием', 'GIL strategies', 'enum switch C-style обязателен'], 0, 'First-class functions.'),
    q('performance', 'Когда имеет смысл Cython/PyO3?', ['горячие CPU участки', 'каждый CRUD', 'логирование', 'конфиг YAML'], 0, 'Нативный код для hotspots.'),
    q('performance', 'Профилирование CPU: стандартно…', ['cProfile / pyinstrument', 'print time только в проде без меры', 'gc.collect loop', 'dis всегда'], 0, 'Измеряй до оптимизации.'),
    q('performance', 'tracemalloc помогает…', ['искать утечки аллокаций', 'ускорить network', 'убрать GIL', 'форматировать JSON'], 0, 'Трассировка аллокаций.'),
    q('caching', 'Кэш с вытеснением вручную часто на…', ['OrderedDict / functools.lru_cache', 'list.pop(0) как LRU идеал', 'set', 'queue.Queue only'], 0, 'move_to_end паттерн.'),
    q('design', 'Fail fast означает…', ['рано обнаруживать ошибки', 'глотать exceptions', 'retry бесконечно', 'lazy import всегда'], 0, 'Быстрый сигнал о проблеме.'),
    q('design', 'Идемпотентность API важна для…', ['безопасных повторов запросов', 'GIL', 'list.sort', 'print'], 0, 'Повтор не меняет эффект.'),
    q('observability', 'Структурированные логи — это…', ['machine-readable поля (JSON и т.п.)', 'только print traceback', 'pickle logs', 'HTML'], 0, 'Удобный поиск/алерты.'),
    q('packaging', 'pyproject.toml — современный…', ['стандарт манифеста сборки (PEP 518/621)', 'только Poetry файл', 'замена requirements без смысла', 'runtime config app'], 0, 'Единая точка конфига пакета.'),
    q('packaging', 'wheel — это…', ['бинарный/готовый дистрибутив пакета', 'исходник tar только', 'venv', 'conda exclusive'], 0, 'PEP 427.'),
    q('packaging', 'abi3 / stable ABI нужен чтобы…', ['одно колесо на несколько версий CPython', 'убрать GIL', 'ускорить import', 'заменить ctypes'], 0, 'Limited API.'),
    q('C-API', 'Capsule в C-API…', ['безопасно передаёт C указатели', 'JSON', 'async handle', 'GIL token'], 0, 'PyCapsule.'),
    q('ctypes', 'ctypes подходит для…', ['вызова C ABI из Python', 'замены asyncio', 'ORM', 'templating'], 0, 'FFI без компиляции расширения.'),
    q('cffi/pybind', 'pybind11/PyO3 — это…', ['обёртки C++/Rust для расширений', 'чистый Python web', 'linters', 'formatters'], 0, 'Нативные модули.'),
    q('subinterpreters', 'PEP 554 / subinterpreters цель…', ['изоляция внутри процесса', 'удаление процессов', 'JS bridge', 'SQL'], 0, 'Меньше shared state.'),
    q('typing', 'reveal_type() используется…', ['в type checkers для отладки типов', 'runtime print type всегда', 'dis', 'gc'], 0, 'mypy/pyright helper.'),
    q('typing', 'cast(T, x) в typing…', ['говорит чекеру тип, runtime no-op', 'конвертирует значение', 'валидирует', 'бросает'], 0, 'Только для статического анализа.'),
    q('runtime', '__getattr__ на модуле (PEP 562)…', ['ленивые атрибуты модуля', 'запрещён', 'только классы', 'GIL hook'], 0, 'Module-level getattr.'),
    q('lazy', 'import внутри функции плюсы…', ['меньше циклов импорта / ленивый старт', 'всегда быстрее', 'обязателен pep8', 'ломает typing всегда'], 0, 'Tradeoff читаемости.'),
    q('exceptions', 'BaseException vs Exception…', ['SystemExit/KeyboardInterrupt не от Exception', 'нет разницы', 'Exception выше', 'BaseException deprecated'], 0, 'Не ловите BaseException широко.'),
    q('signals', 'Обработка сигналов и потоки…', ['сигналы в главном потоке', 'в любом потоке одинаково', 'только asyncio', 'только multiprocessing'], 0, 'Ограничение CPython.'),
    q('fork', 'После fork в многопоточном процессе опасно…', ['состояние locks/threads', 'только print', 'int', 'str intern'], 0, 'Только fork’нувший поток жив.'),
    q('security', 'yaml.load без SafeLoader…', ['может выполнить код (устар. PyYAML)', 'безопасен всегда', 'только JSON', 'не существует'], 0, 'safe_load / SafeLoader.'),
    q('security', 'subprocess с shell=True риск…', ['injection через строку команды', 'только медленнее', 'GIL', 'нет риска'], 0, 'Передавайте list args.'),
    q('architecture', 'Гексагональная архитектура акцентирует…', ['порты/адаптеры, ядро без инфры', 'монолит UI', 'GIL layers', 'один большой модуль'], 0, 'Домен независим от фреймворка.'),
    q('architecture', 'CQRS разделяет…', ['чтение и запись модели/запросов', 'CPU и IO', 'sync async', 'тесты и прод'], 0, 'Command Query Responsibility Segregation.'),
    q('events', 'Outbox pattern нужен для…', ['надёжной публикации событий с БД', 'GUI', 'сортировки', 'GIL'], 0, 'Транзакционная отправка.'),
    q('retries', 'Exponential backoff + jitter чтобы…', ['не долбить сервис синхронно', 'ускорить CPU', 'убрать ошибки навсегда', 'кэшировать GIL'], 0, 'Устойчивость клиентов.'),
    q('idempotency keys', 'Ключ идемпотентности в API…', ['предотвращает дубль эффекта', 'шифрует body', 'заменяет auth', 'сжимает JSON'], 0, 'Повтор POST безопаснее.'),
    q('consistency', 'Read-your-writes — это…', ['гарантия увидеть свои записи', 'strong serializable всегда', 'eventual only', 'GIL'], 0, 'Модель консистентности.'),
    q('python', 'Почему list.pop(0) медленный?', ['O(n) сдвиг элементов', 'O(1) на деле', 'GIL lock N раз', 'hash rebuild'], 0, 'Для очереди — deque.'),
    q('python', 'Почему dict быстрее list для поиска ключа?', ['средний O(1) hash', 'sorted binary всегда', 'GIL', 'intering only'], 0, 'Хеш-таблица.'),
    q('interning', 'Пул малых int диапазон типично…', ['-5..256 в CPython', 'все int', 'только 0,1', 'нет пула'], 0, 'Деталь реализации.'),
    q('string', 'Почему str immutable важно для…', ['безопасности ключей dict / шаринга', 'скорости +=', 'GIL', 'UTF-16'], 0, 'Хешируемость и кэш.'),
    q('async', 'Backpressure в потоках данных — это…', ['ограничение скорости производителя', 'ускорение потребителя магией', 'GIL throttle', 'TCP only term'], 0, 'Не копить бесконечные очереди.'),
    q('queues', 'asyncio.Queue vs queue.Queue?', ['для event loop vs для потоков', 'одно и то же', 'первая для процессов', 'вторая для async'], 0, 'Не смешивать модели.'),
    q('testing', 'Property-based testing (Hypothesis)…', ['генерирует входы по свойствам', 'заменяет unit тесты всегда', 'только UI', 'load test'], 0, 'Поиск контрпримеров.'),
    q('testing', 'Mutation testing проверяет…', ['качество тестов убийством мутантов кода', 'скорость CI', 'типы', 'GIL'], 0, 'Сила тест-сьюта.'),
    q('ci', 'Матрица версий Python в CI нужна чтобы…', ['ловить несовместимости 3.x', 'ускорить один job', 'заменить mypy', 'убрать зависимости'], 0, '3.10/3.11/3.12…'),
    q('api', 'HATEOAS связан с…', ['REST гипермедиа', 'SOAP only', 'GIL', 'CSV'], 0, 'Ссылки в ответах API.'),
    q('rpc', 'gRPC в Python часто через…', ['grpcio + protobuf', 'только json.dumps', 'ftp', 'smtp'], 0, 'Контракты .proto.'),
    q('serialization', 'MessagePack/Protobuf vs JSON когда…', ['нужна компактность/схема/скорость', 'всегда хуже JSON', 'только логи', 'для str keys only'], 0, 'Бинарные протоколы.'),
    q('db', 'N+1 проблема — это…', ['много запросов вместо join/prefetch', 'один огромный SQL', 'GIL waits', 'index miss only'], 0, 'ORM классика.'),
    q('db', 'SELECT FOR UPDATE связан с…', ['блокировкой строк транзакции', 'readonly replica hint always', 'кэшем Redis', 'VACUUM'], 0, 'Пессимистичные блокировки.'),
    q('db', 'MVCC в PostgreSQL даёт…', ['версионность строк для читателей', 'только locks table', 'GIL-like lock', 'columnar only'], 0, 'Мультиверсионность.'),
    q('cache', 'Cache stampede — это…', ['массовый промах кэша одновременно', 'переполнение диска', 'hash collision', 'GIL thrash'], 0, 'Нужны lock/soft expire/singleflight.'),
    q('distributed', 'Consensus (Raft/Paxos) нужен для…', ['согласованного лидера/лога', 'локального dict', 'sort', 'GIL cluster'], 0, 'Распределённые системы.'),
    q('python', 'Плюс __dict__ у экземпляра…', ['гибкость атрибутов', 'всегда меньше памяти чем slots', 'быстрее slots всегда', 'обязателен'], 0, 'Tradeoff гибкость/память.'),
    q('python', 'object.__hash__ по умолчанию основан на…', ['id (идентичности)', 'всех полях', 'str(obj)', 'random'], 0, 'Пока не переопределён eq без hash.'),
    q('CPython', 'Что делает LOAD_FAST в bytecode?', ['загрузка локальной переменной', 'global', 'attr', 'const int always'], 0, 'Быстрый доступ по индексу locals.'),
    q('CPython', 'Почему локальные переменные быстрее глобальных?', ['LOOKUP по индексу vs dict builtins/global', 'GIL иначе работает', 'кэш CPU магия языка', 'интернирование имён'], 0, 'Оптимизация VM.'),
    q('async', 'Cancellation в asyncio Task…', ['CancelledError в await-точке', 'убивает OS thread', 'игнорируется всегда', 'только KeyboardInterrupt'], 0, 'Кооперативная отмена.'),
    q('async', 'shield() защищает…', ['awaitable от отмены снаружи', 'от KeyboardInterrupt', 'от GIL', 'от MemoryError'], 0, 'asyncio.shield.'),
    q('design', 'Антикоррупционный слой…', ['изолирует внешнюю модель от домена', 'логирует SQL', 'кэширует', 'сжимает JSON'], 0, 'DDD.'),
    q('observability', 'OpenTelemetry закрывает…', ['traces/metrics/logs стандарт', 'только APM vendor lock обязательно', 'GIL metrics', 'pip audit'], 0, 'Единый стандарт телеметрии.'),
    q('errors', 'Exception groups (3.11) + except* …', ['работа с несколькими исключениями сразу', 'замена BaseException', 'только asyncio', 'deprecated'], 0, 'PEP 654.'),
    q('typing', 'Self (3.11) в аннотациях…', ['тип текущего класса', 'Any', 'object', 'cls runtime'], 0, 'Удобно для fluent API.'),
    q('perf', 'Инлайн кэш специализации байткода (3.11+)…', ['ускоряет атрибуты/вызовы на горячих путях', 'убирает GIL', 'меняет синтаксис', 'отключает GC'], 0, 'Adaptive interpreter.'),
    q('wasm', 'CPython на WASM ограничивается…', ['sandbox / нет полного OS API', 'скоростью равной native всегда', 'отсутствием int', 'запретом async'], 0, 'Pyodide и др.'),
    q('CPython', 'dict использует открытую адресацию / compact table — зачем знание на собесе?', ['объясняет память и локальность', 'обязательно писать на C', 'заменяет list', 'убирает hash collisions магией'], 0, 'Понимание стоимости операций.'),
    q('CPython', 'code object не содержит…', ['значения heap объектов напрямую как runtime heap graph', 'bytecode', 'consts', 'names'], 0, 'Это шаблон исполнения.'),
    q('GIL', 'Почему numpy.dot больших массивов масштабируется лучше чистого Python цикла в threads?', ['много работы в C без GIL', 'GIL отключён в numpy глобально навсегда', 'threads = processes', 'float быстрее int'], 0, 'Native sections.'),
    q('память', 'tracemalloc.start() влияет на…', ['overhead + возможность снимков аллокаций', 'только скорость сети', 'удаление GIL', 'pickle'], 0, 'Диагностика утечек.'),
    q('память', 'object header минимум содержит…', ['refcount и указатель типа (CPython)', 'только payload', 'только GIL ticket', 'JSON schema'], 0, 'PyObject_HEAD.'),
    q('байткод', 'CACHE / specialized opcodes в 3.11+…', ['ускоряют горячие пути', 'меняют синтаксис языка', 'удаляют exceptions', 'заменяют AST'], 0, 'Adaptive interpreter.'),
    q('дескрипторы', 'Функции в классе становятся bound method через…', ['__get__ дескриптора функции', '__call__ класса', 'GIL', 'import hook'], 0, 'Non-data descriptor.'),
    q('метаклассы', 'type(name, bases, dict) эквивалентен…', ['динамическому созданию класса', 'только eval', 'dataclass', 'Enum'], 0, 'Конструктор классов.'),
    q('метаклассы', '__prepare__ метакласса возвращает…', ['namespace mapping для тела класса', 'MRO', 'GIL state', 'module'], 0, 'Кастомный namespace.'),
    q('typing', 'TypeGuard / TypeIs нужны для…', ['сужения типов в чекере', 'runtime cast всегда', 'GIL', 'скорости'], 0, 'User-defined type guards.'),
    q('typing', 'dataclass_transform помогает…', ['библиотекам-кодогенераторам полей для чекеров', 'ускорить dataclass', 'SQL', 'async'], 0, 'PEP 681.'),
    q('concurrency', 'False sharing — это…', ['контеншн кэш-линий CPU между ядрами', 'GIL false', 'shared list append ok', 'pickle share'], 0, 'Низкоуровневый perf.'),
    q('concurrency', 'Lock в asyncio не блокирует OS-thread, а…', ['паркует корутину', 'убивает loop', 'берёт GIL навсегда', 'spawn process'], 0, 'Кооперативность.'),
    q('asyncio', 'Task cancellation должна быть…', ['корректно обрабатываться в finally', 'проигнорирована всегда', 'мгновенный kill OS', 'только KeyboardInterrupt'], 0, 'Безопасная отмена.'),
    q('asyncio', 'anyio/trio знамениты…', ['structured concurrency идеями', 'удалением async', 'GIL-free CPython', 'ORM'], 0, 'Nurseries/task groups.'),
    q('multiprocessing', 'shared_memory (3.8+) даёт…', ['общий буфер между процессами', 'shared GIL', 'общие произвольные объекты Python transparently', 'TCP'], 0, 'Bytes-like sharing.'),
    q('pickle', 'reduce протокол позволяет…', ['кастомную сериализацию', 'ускорить JSON', 'убрать security risk', 'GIL'], 0, '__reduce__.'),
    q('security', 'ast.literal_eval безопаснее eval потому что…', ['только литералы, не вызовы', 'быстрее', 'одинаково опасен', 'запрещён'], 0, 'Ограниченный парсер.'),
    q('security', 'template injection в Jinja без sandbox риск…', ['RCE через {{ }}', 'только XSS HTML', 'только DoS CPU always', 'нет риска'], 0, 'Не доверяй шаблонам от пользователя.'),
    q('packaging', 'PEP 517 build backend — это…', ['изолированная сборка через pyproject', 'только setup.py exec нативно обязателен', 'pip uninstall', 'venv'], 0, 'Современный build.'),
    q('packaging', 'manylinux wheel гарантирует…', ['ABI совместимость с широким Linux', 'работу на Windows', 'GIL-free', 'мультиязычность'], 0, 'Аудит платформы.'),
    q('architecture', 'Anti-corruption layer переводит…', ['внешнюю модель во внутренний язык домена', 'JSON в XML only', 'sync в async магией', 'SQL в NoSQL auto'], 0, 'DDD boundary.'),
    q('architecture', 'Saga pattern решает…', ['распределённые транзакции через шаги/компенсации', 'локальный GIL', 'UI navigation', 'sort'], 0, 'Вместо 2PC часто.'),
    q('db', 'Repeatable read vs read committed…', ['разный уровень видимости аномалий', 'одно и то же', 'только MySQL term', 'GIL isolation'], 0, 'Изоляция транзакций.'),
    q('db', 'Connection pool нужен чтобы…', ['переиспользовать соединения', 'ускорить JSON', 'убрать индексы', 'заменить ORM'], 0, 'Дорогой handshake.'),
    q('cache', 'Singleflight / request coalescing против…', ['cache stampede', 'LRU', 'TTL', 'CDN only'], 0, 'Один промах — один запрос.'),
    q('distributed', 'Exactly-once на практике часто…', ['at-least-once + идемпотентность', 'гарантия брокера без дизайна', 'только UDP', 'GIL cluster'], 0, 'Реалистичная модель.'),
    q('performance', 'Инлайнинг мелких функций в чистом Python…', ['ограничен интерпретатором; профилируй', 'как в C всегда', 'запрещён', 'делает GIL'], 0, 'Другая модель затрат.'),
    q('performance', 'Когда __slots__ почти не помогает?', ['мало экземпляров / мало атрибутов', 'миллионы объектов с 1 полем', 'всегда помогает 100x', 'только на str'], 0, 'Смотри профиль памяти.'),
    q('observability', 'Span vs metric…', ['span — трейс операции; metric — агрегат', 'одно и то же', 'span только ошибки', 'metric = log line'], 0, 'OpenTelemetry модель.'),
    q('testing', 'Contract tests проверяют…', ['совместимость API между сервисами', 'только UI', 'GIL', 'pep8'], 0, 'Consumer-driven contracts.'),
    q('testing', 'Flaky test чаще лечится…', ['убрать time/race/order dependency', 'увеличить sleep 10s навсегда', 'отключить CI', 'random.seed каждый раз иначе'], 0, 'Детерминизм.'),
    q('api', 'Проблема chatty API…', ['слишком много мелких round-trips', 'один huge payload всегда лучше без меры', 'только GraphQL term', 'GIL'], 0, 'Нужен batch/aggregate.'),
    q('serialization', 'Почему protobuf schema-first…', ['явный контракт и совместимость полей', 'человекочитаемее JSON always', 'без версий', 'медленнее всегда'], 0, 'Эволюция API.'),
    q('python', 'Почему str+= в цикле может быть ок в CPython иногда, но стиль — join?', ['квадратичный риск / читаемость / портабельность', 'join медленнее всегда', '+= запрещён', 'GIL'], 0, 'Пиши join для надёжности.'),
    q('python', 'Интернирование идентификаторов vs произвольных строк…', ['идентификаторы часто interned', 'все str interned always', 'никогда', 'только bytes'], 0, 'Деталь CPython.'),
    q('errors', 'except* vs ExceptionGroup.raise…', ['кроме* распаковывает группу по типам', 'синонимы', 'except* удаляет traceback', 'только sync'], 0, 'Structured exceptions.'),
    q('design', 'Law of Demeter в Python…', ['меньше obj.a.b.c цепочек', 'запрет import', 'один модуль на проект', 'GIL law'], 0, 'Слабая связанность.'),
    q('design', 'Hexagonal: adapters зависят от…', ['портов ядра, не наоборот', 'фреймворка в домене', 'GIL', 'БД схемы в UI'], 0, 'Инверсия зависимостей.'),
    q('Zen', 'import this показывает…', ['Zen of Python', 'sys.path', 'GIL poem', 'PEP 8'], 0, 'Пасхалка с афоризмами.'),
    q('C-API', 'PyErr_Occurred проверяет…', ['установлено ли исключение', 'refcount', 'GIL held?', 'hash'], 0, 'C-API error protocol.'),
    q('ctypes', 'restype/argtypes важны чтобы…', ['правильно маршалить C типы', 'ускорить Python loop 100x', 'убрать GC', 'async'], 0, 'Без них легко UB.'),
    q('subinterpreters', 'Зачем изоляция subinterpreters?', ['меньше shared mutable state в процессе', 'замена Docker', 'удаление async', 'быстрее JSON'], 0, 'Параллелизм без полного multiprocess.'),
    q('fork', 'os.register_at_fork помогает…', ['сбрасывать locks/состояние вокруг fork', 'создать thread', 'GIL off', 'pickle'], 0, 'Безопасный fork.'),
    q('signals', 'signal.set_wakeup_fd связан с…', ['пробуждением loop от сигнала', 'файловым GC', 'HTTP/2', 'typing'], 0, 'Интеграция с asyncio/selectors.'),
    q('lazy', 'MODULE_LEVEL __getattr__ риск…', ['неочевидные ImportError/стоимость', 'всегда быстрее', 'обязателен pep', 'убирает циклы всегда без минусов'], 0, 'Явность vs магия.'),
    q('patterns', 'Registry pattern часто на…', ['dict + декоратор регистрации', 'только metaclass обязателен', 'GIL registry', 'XML'], 0, 'Плагины/handlers.'),
    q('patterns', 'Null Object pattern…', ['объект с no-op поведением вместо None', 'NoneType subclass обязателен', 'Optional ban', 'mock only'], 0, 'Меньше ветвлений.'),
    q('ci', 'pip-audit / safety в CI ловят…', ['известные CVE зависимостей', 'pep8', 'GIL bugs', 'flaky tests'], 0, 'Supply-chain hygiene.'),
    q('wasm', 'Ограничение сокетов/файлов в браузерном Pyodide…', ['sandbox браузера', 'нет int', 'нет list', 'нет функций'], 0, 'Другая среда исполнения.'),
]
